/* UNION ALL*/

-- TODAS AS CONSULTAS DEVEM TER O MESMO NÚMERO DE COLUNAS

SELECT
	ENTIDADE,
	NOME, 
	INSCRICAO_FEDERAL
FROM PESSOAS_FISICAS

UNION ALL

SELECT
	ENTIDADE,
	NOME,
	INSCRICAO_FEDERAL
FROM PESSOAS_JURIDICAS


-- TESTANDO...

SELECT
	'PF' AS TIPO_CLIENTE,
	ENTIDADE AS COD_CLIENTE,
	NOME AS NOME_CLIENTE,
	INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL
FROM PESSOAS_FISICAS

UNION ALL

SELECT
	'PJ' AS TIPO_CLIENTE,
	ENTIDADE AS COD_CLIENTE,
	NOME AS NOME_CLIENTE,
	INSCRICAO_FEDERAL AS INCRICAO_FEDERAL
FROM PESSOAS_JURIDICAS

UNION ALL

SELECT
	'EN' AS TIPO_CLIENTE,
	ENTIDADE AS COD_CLIENTE,
	NOME AS NOME_CLIENTE,
	INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL
FROM ENTIDADES

/* TREINANDO...*/

-- Todas as consultas devem ter devem ter o mesmo número de colunas
-- Todos os tipos de dados devem ser compatíveis entre as colunas
-- Os ALIAS devem ficar no primeiro SELECT
-- ORDER BY sempre vem no primeiro SELECT

SELECT
	'PF' AS TIPO_CLIENTE,
	 ENTIDADE AS COD_CLIENTE,
	 NOME     AS NOME_CLIENTE,
	 INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL,
	 DATA_CADASTRO AS DATA_CADASTRO
FROM PESSOAS_FISICAS

UNION ALL

SELECT
	'PJ' AS TIPO_CLIENTE,
	 ENTIDADE AS COD_CLIENTE,
	 NOME AS NOME_CLIENTE,
	 INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL,
	 NULL
FROM PESSOAS_JURIDICAS

UNION ALL

SELECT
	'EN' AS TIPO_CLIENTE,
	 ENTIDADE AS COD_CLIENTE,
	 NOME AS NOME_CLIENTE,
	 INSCRICAO_FEDERAL AS INSCRICAO_FEDERAL,
	 NULL
FROM ENTIDADES

/* OUTRO EXEMPLO */

SELECT
    'TR' AS TIPO,
	B.ENTIDADE,
	B.NOME, 
	B.INSCRICAO_FEDERAL,
	SUM(A.VALOR) AS VALOR_RECEBER
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION ALL
/* OUTRO EXEMPLO */

SELECT
    'TP' AS TIPO,
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL,
	SUM(A.VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL
ORDER BY ENTIDADE

/* DEIXANDO DE FORMA MAIS ORGANIZADA */

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL,
	SUM(A.VALOR) AS VALOR_RECEBER, 
	0.00 AS VALOR_RECEBER
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION ALL

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL,
	SUM(A.VALOR) AS VALOR_PAGAR,
	0.00 AS VALOR_RECEBER
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL
ORDER BY ENTIDADE

/* APLICAÇÃO DO UNION */

SELECT
	ENTIDADE   AS COD_CLIENTE,
	NOME       AS NOME_CLIENTE,
	INSCRICAO_FEDERAL   AS INSCRICAO_FEDERAL,
	DATA_CADASTRO AS DATA_CADASTRO
FROM PESSOAS_FISICAS

UNION

SELECT
	ENTIDADE,
	NOME,
	INSCRICAO_FEDERAL,
	NULL
FROM PESSOAS_JURIDICAS

UNION

SELECT
	ENTIDADE,
	NOME,
	INSCRICAO_FEDERAL,
	NULL
FROM ENTIDADES

/* REVISANDO */

SELECT
	'PF' AS TIPO,
	ENTIDADE AS COD_CLIENTE,
	NOME     AS NOME_CLIENTE,
	INSCRICAO_FEDERAL  AS INSCRICAO_FEDERAL,
	DATA_CADASTRO
FROM PESSOAS_FISICAS

UNION

SELECT
	'PJ',
	ENTIDADE,
	NOME,
	INSCRICAO_FEDERAL,
	NULL
FROM PESSOAS_JURIDICAS

UNION
SELECT
	'EN',
	ENTIDADE,
	NOME,
	INSCRICAO_FEDERAL,
	NULL
FROM ENTIDADES

/* REVISANDO */

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL,
	SUM(A.VALOR) AS VALOR_RECEBER,
	0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER  A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION ALL
SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL,
	0.00 AS VALOR_RECEBER,
	SUM(A.VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

ORDER BY ENTIDADE

/* EXCEPT */

SELECT
	 B.ENTIDADE,
	 B.NOME,
	 B.INSCRICAO_FEDERAL
FROM TITULOS_PAGAR A
INNER JOIN ENTIDADES B  ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION ALL
SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_RECEBER A
INNER JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

ORDER BY ENTIDADE

/* TESTANDO COM UNION */

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

UNION

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

/* EXCEPT */

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

EXCEPT

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

/* TRAZENDO SOMENTE CLIENTES QUE TÊM TÍTULOS A RECEBER */

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_RECEBER A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

EXCEPT

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_PAGAR A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

/* INTERSECT */

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_RECEBER A
JOIN ENTIDADES  B ON A.ENTIDADE = B.ENTIDADE
GROUP BY  B.ENTIDADE, B.NOME, B.INSCRICAO_FEDERAL

INTERSECT

SELECT
	B.ENTIDADE,
	B.NOME,
	B.INSCRICAO_FEDERAL
FROM TITULOS_PAGAR A 
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE

/* APLICAÇÃO DA SETA */

SELECT * FROM TITULOS_PAGAR
WHERE ENTIDADE IN(1,
1002,
1014,
1018,
1049,
1059,
1084,
1096,
1113,
1115,
1121,
1123,
1130,
1132,
1139,
1140,
1141,
1148,
1149,
1150,
1230,
1274,
1297,
1298,
1321,
1329,
1400,
1415,
1416,
1422,
1424,
1427,
1437,
1442,
1457,
1465,
1467,
1477,
1485,
1490,
1508,
1518,
1522,
1527,
1542,
1551,
1552,
1555,
1557,
1584,
1587,
1589,
1594,
1638,
1654,
1696,
1703,
1718,
1763,
1784,
1788,
1792,
1797,
1799,
1815,
1827,
1829,
1834,
1852,
1862,
1864,
1875,
1876,
1879,
1885,
1891,
1907,
1927,
1947,
1949,
1959,
1983,
1988,
1990,
2031,
2032,
2037,
2067,
2073,
2082,
2089,
2097,
2112,
2117,
2119,
2124,
2129,
2136,
2141,
2153,
2155,
2159,
2172,
2178,
2206,
2212,
2234,
2249,
2262,
2270,
2277,
2304,
2308,
2316,
2322,
2334,
2355,
2363,
2385,
2392,
2425,
2523,
2615,
2616,
2626,
2627,
2648,
2661,
2663,
2674,
2710,
2756,
2764,
2771,
2841,
2900,
2929,
2939,
2964,
2969,
3000,
3003,
3014,
3079,
3083,
3085,
3087,
3095,
3103,
3148,
3166,
3189,
3190,
3197,
3204,
3227,
3272,
3275,
3304,
3536)
