USE PBS_PROCFIT_DADOS
/*DESAFIO UTILIZANDO A TABELA NF_FATURAMENTO*/

SELECT
	PRODUTO,
	QUANTIDADE,
	VALOR_UNITARIO,
	QUANTIDADE * VALOR_UNITARIO AS VALOR_TOTAL_PRODUTO,
	ICMS_ALIQUOTA,
    (QUANTIDADE * VALOR_UNITARIO) * (ICMS_ALIQUOTA/100) AS ICMS_VALOR
	
   FROM NF_FATURAMENTO_PRODUTOS

/*DESAFIO: FAÇA UMA CONSULTA NA TABELA ENTIDADES ONDE O RESULTADO DA SUA QUERY
RETORNE O CAMPO ENTIDADE CONCATENADO COM O CAMPO NOME_FANTASIA*/

SELECT 
	ENTIDADE,
	NOME_FANTASIA,
	CONCAT(ENTIDADE,'-', NOME_FANTASIA) AS RESULT
FROM ENTIDADES

/*NA TABELA PRODUTOS CONCATENE O CAMPO DESCRIÇÃO COM O CAMPO UNIDADE DE MEDIDA*/
 SELECT
	DESCRICAO,
	UNIDADE_MEDIDA,
	CONCAT(DESCRICAO,UNIDADE_MEDIDA) AS RESULT
FROM PRODUTOS

/* ORDENDANDO VALORES*/

SELECT
	PRODUTO,
	MOVIMENTO,
	QUANTIDADE,
	VENDA_BRUTA
FROM VENDAS_ANALITICAS
ORDER BY 1, VENDA_BRUTA DESC

-- DESAFIO
 /* REALIZE UMA CONSULTA NA TABELA ENTIDADES ONDE RETORNE AS COLUNAS:
  1 - ENTIDADE;
  2 - INSCRICAO_FEDERA;
  3 - NOME;
  4 - DATA _CADASTRO
*/
SELECT
	ENTIDADE AS COD_CLIENT,
	INSCRICAO_FEDERAL,
	NOME,
	CONCAT(INSCRICAO_FEDERAL,'-',NOME) AS CLIENTE,
	DATA_CADASTRO
FROM ENTIDADES
ORDER BY DATA_CADASTRO DESC-- DATA MAIS ATUAL PARA A MAIS ANTIGA

/* APLICAÇÃO DE FILTROS*/

SELECT * FROM  ENTIDADES
   WHERE ATIVO <> 'N'
ORDER BY ENTIDADE


SELECT * FROM ENTIDADES
	WHERE ATIVO = 'S'
	ORDER BY ENTIDADE

/* DESAFIO
 Selecione as colunas Especie_Fical; Documento_Numero; Vendedor; Movimento; Produto; Quantidade; Venda_Bruta
 Da tabela Vendas_Analiticas, onde o Movimento seja maior do que a data 01/06/2020 */

 SELECT
    ESPECIE_FISCAL,
	DOCUMENTO_NUMERO,
	CONCAT(ESPECIE_FISCAL,'-',DOCUMENTO_NUMERO) AS DOCUMENTO,
	VENDEDOR,
	MOVIMENTO,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA,
	VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
FROM VENDAS_ANALITICAS
WHERE MOVIMENTO > '2020-06-01'
ORDER BY MOVIMENTO ASC

/* Faça a mesma coisa com o desafio 1, porém filtre apenas o produto com o código igual a 34912,
ordenar por quantidade em ordem decrescente*/

 SELECT
    ESPECIE_FISCAL,
	DOCUMENTO_NUMERO,
	CONCAT(ESPECIE_FISCAL,'-',DOCUMENTO_NUMERO) AS DOCUMENTO,
	VENDEDOR,
	MOVIMENTO,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA,
	VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34912
ORDER BY QUANTIDADE DESC

SELECT
	CIDADE
	FROM ENDERECOS
	WHERE CIDADE LIKE 'S_O paulo'

/* APLICANDO O NOT LIKE - ELE FUNCIONA IGUAL AO <>"*/

SELECT CIDADE
	FROM ENDERECOS
	WHERE CIDADE NOT LIKE 'S_O PAULO'
	ORDER BY CIDADE

/* DESAFIO - BUSQUE NA TABELA ENDEREÇOS TODAS AS CIDADES QUE COMECEM COM A PALAVRA SÃO
TRAGUE APENAS AS COLUNAS CIDADE E ESTADO, INDEPENDENTE DA ACENTUAÇÃO */

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
	WHERE CIDADE LIKE 'S_O'
	ORDER BY CIDADE
/* DESAFIO - RECUPERE TODOS OS CLIENTES DA TABELA ENTIDADES
   ONDE O NOME DO CLIENTE NÃO CONTENHAO TEXTO '00'
   TRAGA APENAS AS COLUNAS NOME E DATA_cADASTRO */

SELECT
	NOME,
	DATA_CADASTRO
FROM ENTIDADES
WHERE NOME NOT LIKE '%00%'


/* DESAFIO - REVISÃO */

SELECT
	ESPECIE_FISCAL,
	DOCUMENTO_NUMERO,
	CONCAT(ESPECIE_FISCAL,DOCUMENTO_NUMERO) AS DOCUMENTO,
	VENDEDOR,
	MOVIMENTO,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA,
	VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
FROM VENDAS_ANALITICAS
ORDER BY MOVIMENTO ASC

/*DESAFIO - REVISÃO*/
/* Busque na tabela endereço todas as palavras que começam pela palavra SAO, traga apenas as colunas cidade e estado*/

SELECT 
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE CIDADE LIKE 'S%O%'

/* DESAFIO 2 */
/* RECUPERE TODOS OS CLIENTES DA TABELA ENTIDADES ONDE O NOME DO CLIENTE NÃO CONTENHA O TEXTO 00
TRAGA APENAS AS COLUNAS NOME E DATA_CADASTRO*/

SELECT
	NOME,
	DATA_CADASTRO
FROM ENTIDADES
WHERE NOME NOT LIKE '%00%'


/* OPERADORES AND e OR*/

SELECT * FROM ENTIDADES
 WHERE ATIVO = 'NULL'
 AND DATA_CADASTRO >= '18/06/2020'
 AND INSCRICAO_FEDERAL NOT LIKE '%0001%'

SELECT * FROM ENTIDADES
	WHERE ATIVO ='N'
   OR DATA_CADASTRO >= '18/06/2020'
   OR INSCRICAO_FEDERAL NOT LIKE '%0001%'

SELECT * FROM ENTIDADES
	WHERE ENTIDADE = 1001
	  OR  ENTIDADE = 1002
	  OR ENTIDADE = 1003

SELECT * FROM ENTIDADES
	WHERE ENTIDADE = 1001
	AND ENTIDADE = 1002
	AND ENTIDADE = 1003

/* UTILIZANDO OS OPERADORES IN e NOT IN */

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE ESTADO = 'CE'
     OR ESTADO = 'SP'
	 OR ESTADO = 'BA'

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE ESTADO IN('CE', 'SP', 'BA')

/* UTILIZANDO O NOT IN*/

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE ESTADO NOT IN('CE','SP','BA')
ORDER BY CIDADE ASC


/* DESAFIO - BUSQUE NA TABELA DE VENDAS ANALÍTICAS AS COLUNAS
CLIENTE; QUANTIDADE, VENDEDOR, PRODUTO, MOVIMENTO */

SELECT
	CLIENTE, -- CÓDIGO DO CLIENTE SEJA 1876 OU 1422 OU 2249 (NUMÉRICO)
	QUANTIDADE, -- SEJA MAIOR DO QUE ZERO
	VENDEDOR, -- SEJA 4 OU 16 (NUMÉRICO)
	PRODUTO, -- SEJA 34726 OU 34304 OU 34394 OU 34593 (NUMÉRICO)
	MOVIMENTO -- ORDENE PELO MOVIMENTO EM ORDEM CRESCENTE (DATA)
FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876,1422,2249)
	AND QUANTIDADE > 0
	OR VENDEDOR = 4
	OR VENDEDOR = 16
	OR PRODUTO = 34726
	OR PRODUTO = 34304
	OR PRODUTO = 34394
	OR PRODUTO = 34593
ORDER BY MOVIMENTO ASC

/* OUTRA ALTERNATIVA*/

SELECT
	CLIENTE, -- CÓDIGO DO CLIENTE SEJA 1876 OU 1422 OU 2249 (NUMÉRICO)
	QUANTIDADE, -- SEJA MAIOR DO QUE ZERO
	VENDEDOR, -- SEJA 4 OU 16 (NUMÉRICO)
	PRODUTO, -- SEJA 34726 OU 34304 OU 34394 OU 34593 (NUMÉRICO)
	MOVIMENTO -- ORDENE PELO MOVIMENTO EM ORDEM CRESCENTE (DATA)
FROM VENDAS_ANALITICAS
WHERE
	CLIENTE IN (1876,1422,2249)
	AND QUANTIDADE > 0
	AND VENDEDOR IN (4,16)
	AND PRODUTO IN (34726,34304,34394,34593)
ORDER BY MOVIMENTO ASC


/* OPERADOR BETWEEN*/

SELECT * FROM ENTIDADES
	WHERE ENTIDADE IN (1001,1002,1003,1004,1005,1006,1007,1008,1009,1010)

SELECT * FROM ENTIDADES
	WHERE ENTIDADE BETWEEN 1001 AND 1010

/* UTILIZADO EM DATAS */

SELECT * FROM ENTIDADES
	WHERE DATA_CADASTRO BETWEEN 1 AND 1010
	ORDER BY DATA_CADASTRO

/* DESAFIO */

/* TABELA VENDAS_ANALITICAS

1 - CLIENTE (1876 OU 1422 OU 2249)
2 - QUANTIDADE > 0
3 - VENDEDOR SEJA 4 OU 16
4 - PRODUTO SEJA 346726 OU  34304 OU 34394 OU 34593

REALIZE A ORDENACAO PELO MOVIMENTO EM ORDEM CRESCENTE */
SELECT 
	CLIENTE,
	QUANTIDADE,
	VENDEDOR,
	PRODUTO,
	MOVIMENTO
	FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876,1422,2249)
      AND QUANTIDADE > 0
	  AND VENDEDOR IN (4,16)
	  AND PRODUTO IN (34726,34304,34394,34593)

ORDER BY MOVIMENTO ASC

/* REVISÃO DO OPERADOR BETWEEEN*/

SELECT * FROM ENTIDADES
WHERE ENTIDADE = 1005
	  OR ENTIDADE = 1001
	  OR ENTIDADE = 1002
	  OR ENTIDADE = 1003
	  OR ENTIDADE = 1004

SELECT * FROM ENTIDADES
WHERE ENTIDADE IN (1001,1002,1003,1004,1005)

SELECT * FROM ENTIDADES
WHERE ENTIDADE BETWEEN 1001 AND 1005

/* SUPER DESAFIO */

/* RETORNE TODOS OS TÍTULOS A RECEBER DO ANO DE 2020 EM DIANTE*/
/* ENTIDADES DE CÓDIGOS 1874,2308,1520*/
/* CAMPO DO TÍTULO TENHA O TEXTO '/1' */
/* VALOR ESTEJA ENTRE 150 E 255,23 */
/* OU O VALOR ESTEJA ENTRE 425,57 E 550,12 */

SELECT 
	MOVIMENTO, -- Data
	ENTIDADE, --  Cod dos Clientes
	TITULO,-- Núm dos títulos
	VALOR -- Valor
	FROM TITULOS_RECEBER
WHERE MOVIMENTO >='01/01/2020'
  AND ENTIDADE IN (1874,2308,1520)
  AND TITULO LIKE '%/1%'
  AND (VALOR BETWEEN 150.00 AND 255.23 OR VALOR BETWEEN 425.57 AND 550.12)

  -- COLANDO ENTRE PARÊNTES, O SQL RODA, PRIORIZA AQUILO QUE VEM ENTRE PARÊNTESES PRIMEIRO

  /* OPERADOR TOP - EVITA VOCÊ TRAZER TODAS AS LINHAS COM SELECT * FROM */

  SELECT TOP 100 
	CLIENTE,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA
  FROM VENDAS_ANALITICAS
  ORDER BY VENDA_BRUTA DESC

  /* PEGANDO O PERCENTUAL DE 10% DAS LINHAS */

  SELECT TOP 10 PERCENT
  CLIENTE,
  PRODUTO,
  QUANTIDADE,
  VENDA_BRUTA
  FROM VENDAS_ANALITICAS
  ORDER BY VENDA_BRUTA DESC

/* OPERADOR DISTINCT - UTILIZADO PARA MANTER SOMENTE VALORES ÚNICOS */

SELECT DISTINCT
	CIDADE
FROM ENDERECOS
WHERE CIDADE NOT LIKE '%0%'
ORDER BY CIDADE