USE PBS_PROCFIT_DADOS
/*DESAFIO UTILIZANDO A TABELA NF_FATURAMENTO*/

SELECT
	PRODUTO,
	QUANTIDADE,
	VALOR_UNITARIO,
	QUANTIDADE * VALOR_UNITARIO AS VALOR_TOTAL_PRODUTO,
	ICMS_ALIQUOTA,
    (QUANTIDADE * VALOR_UNITARIO) * (ICMS_ALIQUOTA/100) AS ICMS_VALOR
	
   FROM NF_FATURAMENTO_PRODUTOS

/*DESAFIO: FAÇA UMA CONSULTA NA TABELA ENTIDADES ONDE O RESULTADO DA SUA QUERY
RETORNE O CAMPO ENTIDADE CONCATENADO COM O CAMPO NOME_FANTASIA*/

SELECT 
	ENTIDADE,
	NOME_FANTASIA,
	CONCAT(ENTIDADE,'-', NOME_FANTASIA) AS RESULT
FROM ENTIDADES

/*NA TABELA PRODUTOS CONCATENE O CAMPO DESCRIÇÃO COM O CAMPO UNIDADE DE MEDIDA*/
 SELECT
	DESCRICAO,
	UNIDADE_MEDIDA,
	CONCAT(DESCRICAO,UNIDADE_MEDIDA) AS RESULT
FROM PRODUTOS

/* ORDENDANDO VALORES*/

SELECT
	PRODUTO,
	MOVIMENTO,
	QUANTIDADE,
	VENDA_BRUTA
FROM VENDAS_ANALITICAS
ORDER BY 1, VENDA_BRUTA DESC

-- DESAFIO
 /* REALIZE UMA CONSULTA NA TABELA ENTIDADES ONDE RETORNE AS COLUNAS:
  1 - ENTIDADE;
  2 - INSCRICAO_FEDERAL ;
  3 - NOME;
  4 - DATA _CADASTRO
*/
SELECT
	ENTIDADE AS COD_CLIENT,
	INSCRICAO_FEDERAL,
	NOME,
	CONCAT(INSCRICAO_FEDERAL,'-',NOME) AS CLIENTE,
	DATA_CADASTRO
FROM ENTIDADES
ORDER BY DATA_CADASTRO DESC-- DATA MAIS ATUAL PARA A MAIS ANTIGA

/* APLICAÇÃO DE FILTROS*/

SELECT * FROM  ENTIDADES
   WHERE ATIVO <> 'N'
ORDER BY ENTIDADE


SELECT * FROM ENTIDADES
	WHERE ATIVO = 'S'
	ORDER BY ENTIDADE

/* DESAFIO
 Selecione as colunas Especie_Fical; Documento_Numero; Vendedor; Movimento; Produto; Quantidade; Venda_Bruta
 Da tabela Vendas_Analiticas, onde o Movimento seja maior do que a data 01/06/2020 */

 SELECT
    ESPECIE_FISCAL,
	DOCUMENTO_NUMERO,
	CONCAT(ESPECIE_FISCAL,'-',DOCUMENTO_NUMERO) AS DOCUMENTO,
	VENDEDOR,
	MOVIMENTO,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA,
	VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
FROM VENDAS_ANALITICAS
WHERE MOVIMENTO > '2020-06-01'
ORDER BY MOVIMENTO ASC

/* Faça a mesma coisa com o desafio 1, porém filtre apenas o produto com o código igual a 34912,
ordenar por quantidade em ordem decrescente*/

 SELECT
    ESPECIE_FISCAL,
	DOCUMENTO_NUMERO,
	CONCAT(ESPECIE_FISCAL,'-',DOCUMENTO_NUMERO) AS DOCUMENTO,
	VENDEDOR,
	MOVIMENTO,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA,
	VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34912
ORDER BY QUANTIDADE DESC

SELECT
	CIDADE
	FROM ENDERECOS
	WHERE CIDADE LIKE 'S_O paulo'

/* APLICANDO O NOT LIKE - ELE FUNCIONA IGUAL AO <>"*/

SELECT CIDADE
	FROM ENDERECOS
	WHERE CIDADE NOT LIKE 'S_O PAULO'
	ORDER BY CIDADE

/* DESAFIO - BUSQUE NA TABELA ENDEREÇOS TODAS AS CIDADES QUE COMECEM COM A PALAVRA SÃO
TRAGUE APENAS AS COLUNAS CIDADE E ESTADO, INDEPENDENTE DA ACENTUAÇÃO */

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
	WHERE CIDADE LIKE 'S_O'
	ORDER BY CIDADE
/* DESAFIO - RECUPERE TODOS OS CLIENTES DA TABELA ENTIDADES
   ONDE O NOME DO CLIENTE NÃO CONTENHAO TEXTO '00'
   TRAGA APENAS AS COLUNAS NOME E DATA_cADASTRO */

SELECT
	NOME,
	DATA_CADASTRO
FROM ENTIDADES
WHERE NOME NOT LIKE '%00%'


/* DESAFIO - REVISÃO */

SELECT
	ESPECIE_FISCAL,
	DOCUMENTO_NUMERO,
	CONCAT(ESPECIE_FISCAL,DOCUMENTO_NUMERO) AS DOCUMENTO,
	VENDEDOR,
	MOVIMENTO,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA,
	VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
FROM VENDAS_ANALITICAS
ORDER BY MOVIMENTO ASC

/*DESAFIO - REVISÃO*/
/* Busque na tabela endereço todas as palavras que começam pela palavra SAO, traga apenas as colunas cidade e estado*/

SELECT 
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE CIDADE LIKE 'S%O%'

/* DESAFIO 2 */
/* RECUPERE TODOS OS CLIENTES DA TABELA ENTIDADES ONDE O NOME DO CLIENTE NÃO CONTENHA O TEXTO 00
TRAGA APENAS AS COLUNAS NOME E DATA_CADASTRO*/

SELECT
	NOME,
	DATA_CADASTRO
FROM ENTIDADES
WHERE NOME NOT LIKE '%00%'


/* OPERADORES AND e OR*/

SELECT * FROM ENTIDADES
 WHERE ATIVO = 'NULL'
 AND DATA_CADASTRO >= '18/06/2020'
 AND INSCRICAO_FEDERAL NOT LIKE '%0001%'

SELECT * FROM ENTIDADES
	WHERE ATIVO ='N'
   OR DATA_CADASTRO >= '18/06/2020'
   OR INSCRICAO_FEDERAL NOT LIKE '%0001%'

SELECT * FROM ENTIDADES
	WHERE ENTIDADE = 1001
	  OR  ENTIDADE = 1002
	  OR ENTIDADE = 1003

SELECT * FROM ENTIDADES
	WHERE ENTIDADE = 1001
	AND ENTIDADE = 1002
	AND ENTIDADE = 1003

/* UTILIZANDO OS OPERADORES IN e NOT IN */

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE ESTADO = 'CE'
     OR ESTADO = 'SP'
	 OR ESTADO = 'BA'

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE ESTADO IN('CE', 'SP', 'BA')

/* UTILIZANDO O NOT IN*/

SELECT
	CIDADE,
	ESTADO
FROM ENDERECOS
WHERE ESTADO NOT IN('CE','SP','BA')
ORDER BY CIDADE ASC


/* DESAFIO - BUSQUE NA TABELA DE VENDAS ANALÍTICAS AS COLUNAS
CLIENTE; QUANTIDADE, VENDEDOR, PRODUTO, MOVIMENTO */

SELECT
	CLIENTE, -- CÓDIGO DO CLIENTE SEJA 1876 OU 1422 OU 2249 (NUMÉRICO)
	QUANTIDADE, -- SEJA MAIOR DO QUE ZERO
	VENDEDOR, -- SEJA 4 OU 16 (NUMÉRICO)
	PRODUTO, -- SEJA 34726 OU 34304 OU 34394 OU 34593 (NUMÉRICO)
	MOVIMENTO -- ORDENE PELO MOVIMENTO EM ORDEM CRESCENTE (DATA)
FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876,1422,2249)
	AND QUANTIDADE > 0
	OR VENDEDOR = 4
	OR VENDEDOR = 16
	OR PRODUTO = 34726
	OR PRODUTO = 34304
	OR PRODUTO = 34394
	OR PRODUTO = 34593
ORDER BY MOVIMENTO ASC

/* OUTRA ALTERNATIVA*/

SELECT
	CLIENTE, -- CÓDIGO DO CLIENTE SEJA 1876 OU 1422 OU 2249 (NUMÉRICO)
	QUANTIDADE, -- SEJA MAIOR DO QUE ZERO
	VENDEDOR, -- SEJA 4 OU 16 (NUMÉRICO)
	PRODUTO, -- SEJA 34726 OU 34304 OU 34394 OU 34593 (NUMÉRICO)
	MOVIMENTO -- ORDENE PELO MOVIMENTO EM ORDEM CRESCENTE (DATA)
FROM VENDAS_ANALITICAS
WHERE
	CLIENTE IN (1876,1422,2249)
	AND QUANTIDADE > 0
	AND VENDEDOR IN (4,16)
	AND PRODUTO IN (34726,34304,34394,34593)
ORDER BY MOVIMENTO ASC


/* OPERADOR BETWEEN*/

SELECT * FROM ENTIDADES
	WHERE ENTIDADE IN (1001,1002,1003,1004,1005,1006,1007,1008,1009,1010)

SELECT * FROM ENTIDADES
	WHERE ENTIDADE BETWEEN 1001 AND 1010

/* UTILIZADO EM DATAS */

SELECT * FROM ENTIDADES
	WHERE DATA_CADASTRO BETWEEN 1 AND 1010
	ORDER BY DATA_CADASTRO

/* DESAFIO */

/* TABELA VENDAS_ANALITICAS

1 - CLIENTE (1876 OU 1422 OU 2249)
2 - QUANTIDADE > 0
3 - VENDEDOR SEJA 4 OU 16
4 - PRODUTO SEJA 346726 OU  34304 OU 34394 OU 34593

REALIZE A ORDENACAO PELO MOVIMENTO EM ORDEM CRESCENTE */
SELECT 
	CLIENTE,
	QUANTIDADE,
	VENDEDOR,
	PRODUTO,
	MOVIMENTO
	FROM VENDAS_ANALITICAS
WHERE CLIENTE IN (1876,1422,2249)
      AND QUANTIDADE > 0
	  AND VENDEDOR IN (4,16)
	  AND PRODUTO IN (34726,34304,34394,34593)

ORDER BY MOVIMENTO ASC

/* REVISÃO DO OPERADOR BETWEEEN*/

SELECT * FROM ENTIDADES
WHERE ENTIDADE = 1005
	  OR ENTIDADE = 1001
	  OR ENTIDADE = 1002
	  OR ENTIDADE = 1003
	  OR ENTIDADE = 1004

SELECT * FROM ENTIDADES
WHERE ENTIDADE IN (1001,1002,1003,1004,1005)

SELECT * FROM ENTIDADES
WHERE ENTIDADE BETWEEN 1001 AND 1005

/* SUPER DESAFIO */

/* RETORNE TODOS OS TÍTULOS A RECEBER DO ANO DE 2020 EM DIANTE*/
/* ENTIDADES DE CÓDIGOS 1874,2308,1520*/
/* CAMPO DO TÍTULO TENHA O TEXTO '/1' */
/* VALOR ESTEJA ENTRE 150 E 255,23 */
/* OU O VALOR ESTEJA ENTRE 425,57 E 550,12 */

SELECT 
	MOVIMENTO, -- Data
	ENTIDADE, --  Cod dos Clientes
	TITULO,-- Núm dos títulos
	VALOR -- Valor
	FROM TITULOS_RECEBER
WHERE MOVIMENTO >='01/01/2020'
  AND ENTIDADE IN (1874,2308,1520)
  AND TITULO LIKE '%/1%'
  AND (VALOR BETWEEN 150.00 AND 255.23 OR VALOR BETWEEN 425.57 AND 550.12)

  -- COLANDO ENTRE PARÊNTES, O SQL RODA, PRIORIZA AQUILO QUE VEM ENTRE PARÊNTESES PRIMEIRO

  /* OPERADOR TOP - EVITA VOCÊ TRAZER TODAS AS LINHAS COM SELECT * FROM */

  SELECT TOP 100 
	CLIENTE,
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA
  FROM VENDAS_ANALITICAS
  ORDER BY VENDA_BRUTA DESC

  /* PEGANDO O PERCENTUAL DE 10% DAS LINHAS */

  SELECT TOP 10 PERCENT
  CLIENTE,
  PRODUTO,
  QUANTIDADE,
  VENDA_BRUTA
  FROM VENDAS_ANALITICAS
  ORDER BY VENDA_BRUTA DESC

/* OPERADOR DISTINCT - UTILIZADO PARA MANTER SOMENTE VALORES ÚNICOS */

SELECT DISTINCT
	CIDADE
FROM ENDERECOS
WHERE CIDADE NOT LIKE '%0%'
ORDER BY CIDADE

/* MÓDULO 04 - TRATANDO VALORES NULL (ISNULL, COALESCE)*/

SELECT CIDADE,
	ESTADO,
	COMPLEMENTO,
	ISNULL(COMPLEMENTO, 'SEM COMPLEMENTO') AS FUNCAO_ISNULL,
	COALESCE(COMPLEMENTO, 'SEM COMPLEMENTO') AS FUNCAO_COALESCE
FROM ENDERECOS

SELECT
	 COALESCE(VENDEDOR,'-1') AS FUNCAO_COALESCE,
	PRODUTO,
	QUANTIDADE

FROM VENDAS_ANALITICAS


SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO,
COALESCE(MUNICIPIO,-1) AS FUNCAO_COALESCE
FROM ENDERECOS
WHERE COALESCE(MUNICIPIO,-1) = -1

/* FILTRANDO VALORES NULL (IS NULL, IS NOT NULL)*/

SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO,
	COALESCE(MUNICIPIO,-1)
FROM ENDERECOS
WHERE COALESCE (MUNICIPIO,-1) = -1

SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO
FROM ENDERECOS
WHERE MUNICIPIO IS NULL


/* RECUPERANDO APENAS VALORES NÃO NULOS */

SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO,
	COALESCE(MUNICIPIO,-1) AS FUNCAO_COALESCE
FROM ENDERECOS
WHERE COALESCE(MUNICIPIO,-1)<>-1

/* APLICANDO NOT NULL*/
SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO,
	COALESCE(MUNICIPIO,-1) AS FUNCAO_COALESCE
FROM ENDERECOS
WHERE MUNICIPIO IS NOT NULL
/* REVISANDO ISNULL & COALESCE*/

SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO,
COALESCE(MUNICIPIO,-1) AS FUNCAO_COALESCE
FROM ENDERECOS
WHERE COALESCE(MUNICIPIO,-1) = -1

/* EVITA...QUE O PAINEL FIQUE COM UMA INFORMAÇÃO FEIA*/
SELECT
	COALESCE(VENDEDOR,-1) AS VENDEDOR,
	PRODUTO,
	QUANTIDADE
FROM VENDAS_ANALITICAS

/* REVISÃO - FILTRANDO VALORES COM ISNULL & IS NOT NULL*/

SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO,
COALESCE(MUNICIPIO,-1)
FROM ENDERECOS
WHERE COALESCE(MUNICIPIO,-1) = -1

SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO
FROM ENDERECOS
WHERE MUNICIPIO IS NULL

/* IS NOT NULL - TRAZENDO AQUILO QUE NÃO É VAZIO */

SELECT
	CIDADE,
	ESTADO,
	MUNICIPIO,
COALESCE(MUNICIPIO,-1) AS FUNCAO_COALESCE
FROM ENDERECOS
WHERE MUNICIPIO IS NOT NULL


/* NULLIF*/
/* APLIQUE O NULL SE...*/

SELECT
	CIDADE,
	ESTADO,
	COMPLEMENTO,
	NULLIF(COMPLEMENTO,'') AS FUNCAO_NULLIF
FROM ENDERECOS

SELECT
	CIDADE,
	ESTADO,
	COMPLEMENTO,
NULLIF(NULLIF(COMPLEMENTO,''), 'CNPJ: 00.029.372/0007-36') AS FUNCAO_NULLIF
FROM ENDERECOS
WHERE NULLIF(NULLIF(COMPLEMENTO,''), 'CNPJ: 00.029.372/0007-36') IS NOT NULL


/* REVISÃO NULLIF*/

SELECT
	CIDADE,
	ESTADO,
	COMPLEMENTO,
	NULLIF(NULLIF(COMPLEMENTO,' '),'CNPJ: 00.029.372/0007-36') AS FUNCAO_NULLIF
FROM ENDERECOS
WHERE NULLIF(NULLIF(COMPLEMENTO,''),'CNPJ: 00.029.372/0007-36') IS NOT NULL


/* ROUND(), FLOOR(),CEILING(), ABS()*/

SELECT TOP 100
	PRODUTO,
	QUANTIDADE,
	VENDA_BRUTA,
	CEILING(VENDA_BRUTA) AS FUNCAO_CEILING,
	FLOOR(VENDA_BRUTA) AS FUNCAO_FLOOR,
	ROUND(VENDA_BRUTA,0) AS FUNCAO_ROUND_0,
	ROUND(VENDA_BRUTA,1) AS FUNCAO_ROUND_1,
	ABS(VENDA_BRUTA) AS FUNCAO_ABS -- TRAZER SOMENTE VALORS POSITIVOS
FROM VENDAS_ANALITICAS
WHERE ABS(CEILING(VENDA_BRUTA)) = 360

/* DESAFIO */
/* ITEM 1*/

/* RECUPERE AS INFORMAÇÕES DE
VENDEDOR,
PRODUTO,
QUANTIDADE,
VALOR_UNITARIO (VENDA_BRUTA DIVIDIDO PELA QUANTIDADE)
VENDA BRUTA
TABELA - VENDAS ANALÍTICAS */

SELECT TOP 100
	COALESCE(VENDEDOR,0) , /* CASO O VENDEDOR FOR NULL, O VALOR DEVE SER ZERO*/
	PRODUTO,
	QUANTIDADE,
	ROUND(VENDA_BRUTA/QUANTIDADE,2) AS VALOR_UNITARIO,
	VENDA_BRUTA
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
ORDER BY VALOR_UNITARIO DESC

/* YEAR, MONTH, DAY*/

SELECT GETDATE() AS DATA_HORA_ATUAL,
	YEAR(GETDATE()) AS ANO,
	MONTH(GETDATE()) AS MES,
	DAY(GETDATE()) AS DIA


SELECT
	NOME,
	DATA_CADASTRO,
	YEAR(DATA_CADASTRO) AS ANO_CADASTRO,
	MONTH(DATA_CADASTRO) AS MES_CADASTRO,
	DAY(DATA_CADASTRO) AS DIA_CADASTRO
FROM ENTIDADES
ORDER BY ANO_CADASTRO

/* APLICAÇÃO DA FUNÇÃO DATEPART*/

SELECT NOME,
  DATA_CADASTRO,
  DATEPART(YEAR, DATA_CADASTRO) AS ANO_CADASTRO,
  DATEPART(WEEKDAY, DATA_CADASTRO) AS DIA_SEMANA_CADASTRO,
  DATEPART(HOUR, GETDATE()) AS HORA,
  DATEPART(MINUTE, GETDATE()) AS MINUTO,
  DATEPART(DAYOFYEAR, DATA_CADASTRO) AS DIA_ANO
FROM ENTIDADES
ORDER BY  ANO_CADASTRO

/* NOVO TREINO*/
/*GETDATE()*/

SELECT GETDATE() AS DATA_HORA_ATUAL,
	YEAR(GETDATE()) AS ANO,
	MONTH(GETDATE()) AS MÊS,
	DAY(GETDATE()) AS DIA


/* YEAR, MONTH, DAY*/

SELECT
	DATA_CADASTRO,
	YEAR(DATA_CADASTRO)AS ANO,
	MONTH(DATA_CADASTRO) AS MÊS,
	DAY(DATA_CADASTRO) AS DIA
FROM ENTIDADES


/* APLICAÇÃO DA FUNÇÃO DATEPART*/

SELECT
	DATA_CADASTRO,
	DATEPART(YEAR, DATA_CADASTRO) AS ANO,
	DATEPART(MONTH, DATA_CADASTRO) AS MÊS,
	DATEPART(DAY, DATA_CADASTRO) AS DIA
FROM ENTIDADES

/* APLICAÇÃO DA DATEADD*/

SELECT GETDATE() AS DATA_HORA_ATUAL,
YEAR(GETDATE()) AS ANO,
MONTH(GETDATE()) AS MÊS,
DAY(GETDATE()) AS DIA,
DATEPART(HOUR,GETDATE()) AS HORAS,
DATEPART(MINUTE, GETDATE()) AS MINUTO,
DATEPART(WEEK, GETDATE()) AS SEMANA,
DATEPART(WEEKDAY, GETDATE()) AS DIA_DA_SEMANA,
DATEADD(YEAR, 1, GETDATE()) AS ANO_1,
DATEADD(DAY,1,GETDATE()) AS DIA_1,
DATEADD(YEAR, -1, GETDATE()) AS ANO_PASSADO

/* OUTROS EXEMPLOS*/
/*DATEADD*/
SELECT
	TITULO,
	VENCIMENTO,
	DATEADD(DAY,10, VENCIMENTO) AS NOVA_DATA_VENCIMENTO
FROM TITULOS_RECEBER

/*DATEDIFF - NOS RETORNA A DIFERENÇA*/

SELECT
	NOME,
	DATA_CADASTRO,
	DATEDIFF(YEAR, DATA_CADASTRO, GETDATE()) AS DIFERENCA_ANOS,
	CONCAT(DATEDIFF(YEAR, DATA_CADASTRO, GETDATE()), ' ANOS') AS DIFERENCA_ANOS,
	CONCAT(DATEDIFF(DAY, DATA_CADASTRO, GETDATE()), ' DIAS') AS DIFERENCA_DIAS,
	CONCAT(DATEDIFF(MONTH, DATA_CADASTRO, GETDATE()), ' MESES') AS DIFERENCA_MESES
FROM ENTIDADES

SELECT
	TITULO,
	MOVIMENTO,
	VENCIMENTO,
	DATEDIFF(DAY, MOVIMENTO, VENCIMENTO) AS DIFERENCA_DIAS,
	CONCAT(DATEDIFF(DAY, MOVIMENTO, VENCIMENTO), ' DIAS DE VENCIMENTO') AS DIFERENCA
FROM TITULOS_RECEBER

/*EOMONTH*/

SELECT
	TITULO,
	MOVIMENTO,
	VENCIMENTO,
	CONCAT(DATEDIFF(DAY, MOVIMENTO, VENCIMENTO),'  DIAS DE PRAZO' ) AS PRAZO,
	EOMONTH(MOVIMENTO) AS ULTIMA_DATA_MES,
	DAY(EOMONTH(MOVIMENTO)) AS ULTIMO_DIA
FROM TITULOS_RECEBER

/* MANIPULANDO CAMPOS DE TEXTO (UPPER, LOWER, REPLACE, LEN) */
SELECT NOME,
	UPPER(NOME) AS LETRAS_MAIUSCULAS,
	LOWER(NOME_FANTASIA) AS LETRAS_MINUSCULAS,
	REPLACE(NOME,'CLIENTE ',' ') AS FUNCAO_REPLACE,
	REPLACE(NOME, 'ente ','_') AS FUNCAO_REPLACE2,
	LEN(NOME) AS QUANTIDADE_CARACTERES
FROM ENTIDADES

/* LEFT, RIGHT, SUBSTRING */

SELECT
	NOME,
	LEFT(NOME, 7) AS ESQUERDA,
	RIGHT(NOME, 4) AS DIREITA,
	SUBSTRING(NOME,4,3) AS FUNCAO_SUBSTRING, /* A PARTIR DO 4º, ME TRAGA 3 CARACTERES*/
	SUBSTRING(NOME,1,7) AS FUNCAO_SUBSTRING
FROM ENTIDADES

/* REVISANDO A AULA AUTERIOR*/

/*LEFT, RIGHT, SUBSTRING*/

SELECT
	NOME,
	LEFT(NOME,7) AS ESQUERDA,
	RIGHT(NOME,4) AS DIREITA,
	SUBSTRING(NOME,1,CHARINDEX(' ',NOME) -1) AS SUBS
FROM ENTIDADES


/* RTRIM, LTRIM, TRIM, CHARINDEX, LEN*/

SELECT
	NOME,
	LEFT(NOME,7) AS NOME,
	CHARINDEX(' ', NOME) AS POSICAO_ESPACO,
	SUBSTRING(NOME,1,CHARINDEX(' ',NOME) -1) AS NOME_AUTO,
	RIGHT(NOME,4) AS SOBRENOME_MANU,
	SUBSTRING(NOME,CHARINDEX(' ',NOME) +1, LEN(NOME) - CHARINDEX(' ', NOME)) AS SOBRENOME_AUTO
FROM ENTIDADES

/*DESAFIO*/

/* RECUPERE DA TABELA TÍTULO_RECEBER AS COLUNAS
ENTIDADE, TITULO, DOCUMENTOS, PARCELAS, PRAZO

APENAS DA ENTIDADE CÓDIGO 1824

SEGUINDO AS SEGUINTES REGRAS
1 - O DOCUMENTO É O VALOR CONTIDO NO CAMPO TÍTULO ANTES DA "/"
2 - A PARCELA É O VALOR CONTIDO NO CAMPO TÍTULO APÓS A "/"
3 - O PRAZO É A DIFERENÇA EM DIAS ENTRE O MOVIMENTO E O VENCIMENTO
4 - ORDENE AS INFORMAÇÕES PELO PRAZO EM ORDEM DECRESCENTE */

SELECT
	ENTIDADE,
	TITULO,
	DOCUMENTO,
	--SUBSTRING(TITULO,1,CHARINDEX('/',TITULO) -1) AS DOC
	SUBSTRING(TITULO,CHARINDEX('/',TITULO) +1, LEN(TITULO) - CHARINDEX('/',TITULO)) AS PARCELA,
	DATEDIFF(DAY,MOVIMENTO,VENCIMENTO) AS PRAZO
FROM TITULOS_RECEBER
WHERE ENTIDADE = 1824
ORDER BY PRAZO DESC

/* REVISÃO BÁSICA*/

SELECT
	UPPER(NOME) AS LETRAS_MAIUSCULAS,
	LOWER(NOME) AS LETRAS_MINUSCULAS,
	REPLACE(NOME, 'Cliente',' ') AS FUNCAO_REPLACE,
	LEN(NOME) AS QUANTIDADE_CARACTERES
FROM ENTIDADES


/* OUTRA REVISÃO BÁSICA*/

SELECT
	NOME,
	LEFT(NOME,7) AS ESQ,
	RIGHT(NOME,4) AS DIR,
	SUBSTRING(NOME,4,3) AS SUB
FROM ENTIDADES



/* FUNÇÕES DE AGREGAÇÃO*/
/*SUM, MAX, MIN, AVG*/


/* TOTAL VENDIDO POR PRODUTO*/
SELECT
	PRODUTO,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
GROUP BY PRODUTO

/* TOTAL VENDIDO POR PRODUTO E POR CLIENTE*/

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
GROUP BY PRODUTO, CLIENTE

/* QUANTIDADE MÍNIMA VENDIDA*/

SELECT
 MIN(QUANTIDADE) AS MINIMO
 FROM VENDAS_ANALITICAS

 /* QUANTIDADE MÁXIMA VENDIDA*/

 SELECT
	MAX(QUANTIDADE) AS MAXIMO
FROM VENDAS_ANALITICAS

/* MIN E MAX POR PRODUTO*/

SELECT
	MIN(QUANTIDADE) AS MINIMO,
	MAX(QUANTIDADE) AS MAXIMO,
	PRODUTO
FROM VENDAS_ANALITICAS
GROUP BY PRODUTO

/* ANALISANDO QUANTIDADE VENDIDA POR UM PRODUTO ESPECÍFICO*/

SELECT
	PRODUTO,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO

/* ANALISANDO QUANTIDADE VENDIDA POR UM PRODUTO ESPECÍFICO E AINDA POR CLIENTE*/

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE

/* COUNT - SERVE PARA  CONTAR VALORES */

SELECT
	COUNT(*) AS TOTAL_LINHAS
FROM VENDAS_ANALITICAS

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO,
	COUNT(*) AS QUANTIDADE_COMPRAS,
	AVG(QUANTIDADE) AS MEDIA_VENDAS,
	SUM(QUANTIDADE)/COUNT(*) AS MEDIA_VENDAS_MAN
FROM VENDAS_ANALITICAS
GROUP BY PRODUTO,CLIENTE

/* VENDO A QUANTIDADE COMPRADA SOMENTE NO ITEM 3159*/

SELECT * FROM VENDAS_ANALITICAS
WHERE PRODUTO = 3159
AND CLIENTE = 2468

/* APLICAÇÃO DO HAVING*/

SELECT
 PRODUTO,
 CLIENTE,
 SUM(QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
  AND QUANTIDADE > 10
GROUP BY PRODUTO, CLIENTE

/* COM HAVING A GENTE PERCEBE A DIFERENÇA*/

SELECT
 PRODUTO,
 CLIENTE,
 SUM(QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE
 HAVING SUM(QUANTIDADE) > 10

/* OUTRA FORMA*/

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS QUANTIDADE,
	SUM(VENDA_BRUTA) AS VENDA_BRUTA
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE
HAVING SUM(QUANTIDADE) > 10
AND SUM(VENDA_BRUTA) > 65
ORDER BY QUANTIDADE

/*REVISANDO...*/

SELECT
	SUM(QUANTIDADE)
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902


SELECT
	PRODUTO,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
GROUP BY PRODUTO

SELECT
	PRODUTO,
	CLIENTE,
SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO,CLIENTE

/* QUANTIDADE MÍNIMA E MÁXIMA*/

SELECT
	MIN(QUANTIDADE) AS MINIMO,
	MAX(QUANTIDADE) AS MAXIMA
FROM VENDAS_ANALITICAS

/* MIN E MÁX POR PRODUTO*/

SELECT
	MIN(QUANTIDADE) AS MINIMO,
	MAX(QUANTIDADE) AS MAXIMO,
	PRODUTO
FROM VENDAS_ANALITICAS
GROUP BY PRODUTO

/* ANALISANDO QUANTIDADE VENDIDA POR UM PRODUTO ESPECÍFICO*/

SELECT
	PRODUTO,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO

/* ANALISANDO QUANTIDADE VENDIDA POR UM PRODUTO ESPECÍFICO E ADICIONANDO CLIENTE*/

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE

/* APLICAÇÃO DO COUNT - SERVE PARA CONTAR VALORES*/

SELECT
	COUNT(*) AS TOTAL_LINHAS
FROM VENDAS_ANALITICAS

/* GERAL*/

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS TOTAL_VENDIDO,
	COUNT(*) AS QUANTIDADE_COMPRAS,
	AVG(QUANTIDADE) AS MEDIA_VENDAS,
	SUM(QUANTIDADE)/COUNT(*) AS MEDIA_VENDAS_MAN
FROM VENDAS_ANALITICAS
GROUP BY PRODUTO, CLIENTE

/* COUNT AND COUNT DISTINCT*/

SELECT
	COUNT(PRODUTO) AS TOTAL_LINHAS
FROM VENDAS_ANALITICAS

SELECT
	COUNT(DISTINCT PRODUTO) AS LINHAS_DISTINTAS
FROM VENDAS_ANALITICAS

/* HAVING */
SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE

/* FILTRANDO VALORES QUE DERAM ACIMA DE 10*/

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
AND QUANTIDADE > 10
GROUP BY PRODUTO, CLIENTE

/* FILTRANDO COM HAVING, OU SEJA, FILTRANDO VALORES QUE ESTÃO AGRUPADOS*/

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE
HAVING SUM(QUANTIDADE) > 10

/* UTILIZANDO 2 HAVING */

SELECT
	CLIENTE,
	SUM(QUANTIDADE) AS QUANTIDADE,
	SUM(VENDA_BRUTA) AS VENDA_BRUTA
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE
ORDER BY QUANTIDADE

SELECT
	PRODUTO,
	CLIENTE,
	SUM(QUANTIDADE) AS QUANTIDADE,
	SUM(VENDA_BRUTA) AS VENDA_BRUTA
FROM VENDAS_ANALITICAS
WHERE PRODUTO = 34902
GROUP BY PRODUTO, CLIENTE
HAVING SUM(QUANTIDADE) > 10 AND SUM(VENDA_BRUTA) > 65
ORDER BY QUANTIDADE

/* DESAFIO*/

 -- RECUPERE AS INFORMAÇÕES DE:
 -- CLIENTE, QUANTIDADE_TOTAL (SOMA DA COLUNA QUANTIDADE)
 -- VENDA_LIQUIDA_TOTAL (SOMA DA COLUNA VENDA_LIQUIDA)
 -- ITENS_COMPRADOS (CONTAGEM DISTINTA DOS PRODUTOS ADQUIRIDOS PELO CLIENTE

 SELECT
	CLIENTE,
	SUM(QUANTIDADE) AS QUANTIDADE_TOTAL,
	SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA_TOTAL,
	COUNT(DISTINCT PRODUTO) AS ITENS_COMPRADOS
FROM VENDAS_ANALITICAS
WHERE VENDEDOR = 1
GROUP BY CLIENTE
HAVING COUNT(DISTINCT PRODUTO) > 50
ORDER BY ITENS_COMPRADOS DESC

/* APLICANDO O USO DO CASE*/
SELECT
	COALESCE(VENDEDOR,0) AS VENDEDOR,
	VENDA_LIQUIDA,
CASE
	WHEN VENDA_LIQUIDA <=0
	   THEN 'SEM COMISSÃO'
	WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
	   THEN '1%'
	WHEN VENDA_LIQUIDA >= 501 AND VENDA_LIQUIDA <= 10000
		THEN'2%'
	WHEN VENDA_LIQUIDA > 10000
		THEN '3%'
	ELSE '4%'
END AS COMISSAO_APLICADA

FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL

/* DEIXANDO O RESULTADO COMO VALOR NUMÉRICO*/

SELECT
	VENDEDOR,
	VENDA_LIQUIDA,
CASE
	WHEN VENDA_LIQUIDA <=0
		THEN 0.00
	WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
		THEN VENDA_LIQUIDA * 1/100
	WHEN VENDA_LIQUIDA >= 500 AND VENDA_LIQUIDA <= 10000
		THEN VENDA_LIQUIDA *2/100
	ELSE VENDA_LIQUIDA * 3/100
END AS VALOR_COMISSAO
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
ORDER BY VALOR_COMISSAO DESC

/* OUTRAS FORMAS*/

SELECT
	VENDEDOR,
	SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
  AND MOVIMENTO BETWEEN '01/01/2020' AND '31/01/2020'
  GROUP BY VENDEDOR


 SELECT
	VENDEDOR,
	SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA,
	CASE	
		WHEN SUM(VENDA_LIQUIDA) <=0
			THEN 'SEM COMISSÃO'
		WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
			THEN '1%'
		WHEN SUM(VENDA_LIQUIDA) >= 501 AND SUM(VENDA_LIQUIDA) <= 10000
			THEN '2%'
		ELSE '3%'
	END AS COMISSAO_APLICADA
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
	AND MOVIMENTO BETWEEN '01/01/2020' AND '31/01/2020'
GROUP BY VENDEDOR

/* CÓDIGO FULL*/

SELECT
	VENDEDOR,
	VENDA_LIQUIDA,
CASE
	WHEN VENDA_LIQUIDA <=0
		THEN 'SEM COMISSÃO'
	WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
		THEN '1%'
	WHEN VENDA_LIQUIDA >= 501 AND VENDA_LIQUIDA <= 10000
		THEN '2%'
	ELSE '3%'
END AS COMISSAO_APLICADA,
CASE
	WHEN VENDA_LIQUIDA <=0
		THEN 0.00
	WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
		THEN VENDA_LIQUIDA * 1/100
	WHEN VENDA_LIQUIDA >= 501 AND VENDA_LIQUIDA <=10000
		THEN '2%'
	ELSE '3%'
END AS VALOR_COMISSAO

FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL

/* FULL COM AGREGAÇÃO */
SELECT
	VENDEDOR,
	SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA,
	CASE
		WHEN SUM(VENDA_LIQUIDA) <=0
			THEN 'SEM COMISSÃO'
		WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
			THEN '1%'
		WHEN SUM(VENDA_LIQUIDA) >= 501 AND SUM(VENDA_LIQUIDA) <=10000
			THEN '2%'
		ELSE '3%'
	END AS COMISSAO_APLICADA,
	
	CASE
		WHEN SUM(VENDA_LIQUIDA) <=0
			THEN 0.00
		WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
			THEN SUM(VENDA_LIQUIDA) * 1/100
		WHEN SUM(VENDA_LIQUIDA) >= 501 AND SUM(VENDA_LIQUIDA) <=10000
			THEN SUM(VENDA_LIQUIDA) * 2/100
		ELSE SUM(VENDA_LIQUIDA) * 3/100
	END AS VALOR_COMISSAO
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
	AND MOVIMENTO BETWEEN '01/01/2020' AND '31/01/2020'
GROUP BY VENDEDOR
HAVING
	CASE
		WHEN SUM(VENDA_LIQUIDA) <=0
			THEN 0.00
		WHEN SUM(VENDA_LIQUIDA) >= 500 AND SUM(VENDA_LIQUIDA) <= 10000
			THEN SUM(VENDA_LIQUIDA) * 2/100
		ELSE SUM(VENDA_LIQUIDA) * 3/100
	END >25000

 /* REVISÃO CASE WHEN */

 SELECT
	VENDEDOR,
	VENDA_LIQUIDA,
CASE
	WHEN VENDA_LIQUIDA <=0
		THEN 'SEM COMISSÃO'
	WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
		THEN '1%'
	WHEN VENDA_LIQUIDA >= 501 AND VENDA_LIQUIDA <= 10000 -- BETWEEN 501 AND 10000
		THEN '2%'
	ELSE '3%'
END AS COMISSAO_APLICADA
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL

/* APLICANDO JUNTO COM AS FUNÇÕES DE AGREGAÇÃO*/

SELECT
	VENDEDOR,
	SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA,
CASE
	WHEN SUM(VENDA_LIQUIDA) <=0
		THEN 'SEM COMISSÃO'
	WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
		THEN '1%'
	WHEN SUM(VENDA_LIQUIDA) >= 501 AND SUM(VENDA_LIQUIDA) <= 10000
		THEN '2%'
	ELSE '3%'
END AS COMISSAO_APLICADA
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
 AND MOVIMENTO BETWEEN '01/01/2020 ' AND '31/01/2020'
 GROUP BY VENDEDOR

 /* APLICANDO A REGRA DE NEGÓCIO SOMENTE COM QUEM TEM COMISSÃO DE 3%*/

 SELECT
	VENDEDOR,
	VENDA_LIQUIDA,
CASE
	WHEN VENDA_LIQUIDA <=0
		THEN 'SEM COMISSÃO'
	WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
		THEN '1%'
	WHEN VENDA_LIQUIDA >= 501 AND VENDA_LIQUIDA <=10000
		THEN '2%'
	ELSE '3%'
END AS COMISSAO_APLICADA,

CASE
	WHEN VENDA_LIQUIDA <=0
		THEN 0.00
	WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
		THEN VENDA_LIQUIDA * 1/100
	WHEN VENDA_LIQUIDA >= 501 AND VENDA_LIQUIDA <= 10000
		THEN VENDA_LIQUIDA * 2 /100
	ELSE VENDA_LIQUIDA * 3/100
END AS VALOR_COMISSAO

FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
 AND CASE
		WHEN VENDA_LIQUIDA <=0
		  THEN 'SEM COMISSÃO'
		WHEN VENDA_LIQUIDA BETWEEN 1 AND 500
			THEN '1%'
		WHEN VENDA_LIQUIDA >=501 AND VENDA_LIQUIDA <= 10000
			THEN '2%'
		ELSE '3%'
	END = '3%'

/* FILTRANDO POR MEIO DA CLÁUSULA HAVING */
SELECT
	VENDEDOR,
	SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA,
CASE
	WHEN SUM(VENDA_LIQUIDA) <=0
		THEN 'SEM COMISSÃO'
	WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
		THEN '1%'
	WHEN SUM(VENDA_LIQUIDA) >= 501 AND SUM(VENDA_LIQUIDA) <= 10000 -- BETWEEN 501 AND 10000
		THEN '2%'
	ELSE '3%'
END AS COMISSAO_APLICADA,

CASE
	WHEN SUM(VENDA_LIQUIDA) <= 0
		THEN 0.00
	WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
		THEN SUM(VENDA_LIQUIDA) * 1/100
	WHEN SUM(VENDA_LIQUIDA) >= 501 AND SUM(VENDA_LIQUIDA) <= 10000
		THEN SUM(VENDA_LIQUIDA) * 2/100
	ELSE SUM(VENDA_LIQUIDA) * 3/100
END AS VALOR_COMISSAO
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL
	AND MOVIMENTO BETWEEN '01/01/2020' AND '31/01/2020'
GROUP BY VENDEDOR
HAVING
	CASE
		WHEN SUM(VENDA_LIQUIDA) <=0
			THEN 0.00
		WHEN SUM(VENDA_LIQUIDA) BETWEEN 1 AND 500
			THEN SUM(VENDA_LIQUIDA) * 1/100
		WHEN SUM(VENDA_LIQUIDA) >= 501 AND SUM (VENDA_LIQUIDA) <= 10000
			THEN SUM(VENDA_LIQUIDA) * 2/100
		ELSE SUM(VENDA_LIQUIDA) * 3/100
	END > 25000


	/* USO DO IIF*/

SELECT
	VENDEDOR,
	QUANTIDADE,
CASE
	WHEN QUANTIDADE > 0
		THEN 'Venda'
	ELSE 'Devolução'
END AS TIPO
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL

SELECT
	VENDEDOR,
	QUANTIDADE,
CASE
	WHEN QUANTIDADE>0
		THEN 'VENDA'
	ELSE 'DEVOLUÇÃO'
END AS TIPO,
IIF(QUANTIDADE >0,'VENDA', 'DEVOLUÇÃO') AS NOVO_IFF
FROM VENDAS_ANALITICAS
WHERE VENDEDOR IS NOT NULL

/* APLICANOD O IIF ANINHADO*/

SELECT
	VENDEDOR,
	QUANTIDADE,
CASE
	WHEN QUANTIDADE <=0
		THEN 'Menor ou igual a zero'
	WHEN QUANTIDADE < 100
		THEN 'Menor que 100'
ELSE 'Maior ou igual a 100'
END,

IIF(QUANTIDADE <=0, 'Menor ou igual a Zero',IIF(QUANTIDADE < 100, 'Menor que 100', 'Maior ou igual a 100'))
FROM VENDAS_ANALITICAS
WHERE VENDEDOR  IS NOT NULL

/* CAST AND CONVERT */
SELECT
	PRODUTO,
	ROUND(VENDA_LIQUIDA/QUANTIDADE,2),
	CAST(ROUND(VENDA_LIQUIDA/QUANTIDADE, 2) AS NUMERIC(9,2)) AS VALOR_UNITARIO,
	CONVERT(NUMERIC(9,2), ROUND(VENDA_LIQUIDA/QUANTIDADE,2)) AS TIPO_CONVERT
FROM VENDAS_ANALITICAS

SELECT
	ENTIDADE,
	DATA_CADASTRO,
	CAST(DATA_CADASTRO AS DATE) AS TIPO_CAST,
	CONVERT(DATE, DATA_CADASTRO) AS TIPO_CONVERT1,
	CONVERT(VARCHAR, DATA_CADASTRO, 103) AS TIPO_CONVERT2
FROM ENTIDADES

/* PROBLEMA DAS CASAS DECIMAIS*/
SELECT
	PRODUTO,
	ROUND(VENDA_LIQUIDA/QUANTIDADE, 2) AS VALOR_UNITARIO,
	CAST(ROUND(VENDA_LIQUIDA/QUANTIDADE, 2) AS NUMERIC (9,2)) AS VALOR_UNITARIO
FROM VENDAS_ANALITICAS

/* CAMPOS DE DATA*/

SELECT
	ENTIDADE,
	CAST(DATA_CADASTRO AS DATE),
	CONVERT(DATE, DATA_CADASTRO),
	CONVERT(VARCHAR, DATA_CADASTRO, 103)
FROM ENTIDADES


/* CAST E CONVERT*/
SELECT
	PRODUTO, 
	ROUND(VENDA_LIQUIDA/QUANTIDADE,2),
	CAST(ROUND(VENDA_LIQUIDA/QUANTIDADE, 2) AS NUMERIC(9,2)) AS VALOR_UNITARIO,
	CONVERT(NUMERIC(9,2), ROUND(VENDA_LIQUIDA/QUANTIDADE,2))
FROM VENDAS_ANALITICAS

/* DATAS E DATAS*/
SELECT
	ENTIDADE,
	DATA_CADASTRO,
	CAST(DATA_CADASTRO AS DATE),
	CONVERT(DATE, DATA_CADASTRO) AS TIPO_CONVERT1,
	CONVERT(VARCHAR, DATA_CADASTRO, 103) AS DATA_3 /* SÓ QUE AQUI TEMOS O TIPO DE TEXTO*/
FROM ENTIDADES
ORDER BY DATA_CADASTRO

/* TRY_CAST - Tente converter*/

SELECT
	ENTIDADE,
	TRY_CAST(NOME AS INT)
FROM ENTIDADES


/* 1..2...3 testando...*/

SELECT
	PRODUTO,
	ROUND(VENDA_LIQUIDA/QUANTIDADE,2) AS TIPO1,
	CAST(ROUND(VENDA_LIQUIDA/QUANTIDADE,2) AS NUMERIC(9,2)) AS TIPO2,
	CONVERT(NUMERIC(9,2), ROUND(VENDA_LIQUIDA/QUANTIDADE,2)) AS TIPO3
FROM VENDAS_ANALITICAS

/* DESAFIO */
-- Recupere as informações de: Vendedor, Média de Vendas, Tipo de Vendas
-- Tabela Vendas_Analiticas, apenas vendedor de código 16, do ano de 2020 em diante
-- A média de vendas é uma média aritmética da coluna venda_liquida

SELECT
	MOVIMENTO,
	VENDEDOR,
	OPERACAO_FISCAL,
	QUANTIDADE,
	AVG(VENDA_LIQUIDA) AS MEDIA_VENDAS,
CASE
	WHEN QUANTIDADE < 0
		THEN 'Devolução'
	WHEN OPERACAO_FISCAL = 12 OR OPERACAO_FISCAL = 14
		THEN 'Venda_Interna'
	ELSE 'Venda Externa'
END AS OPERACOES
FROM VENDAS_ANALITICAS
WHERE VENDEDOR = 16 AND MOVIMENTO >= '2020-01-01'
GROUP BY
	VENDEDOR,OPERACAO_FISCAL, QUANTIDADE, MOVIMENTO
ORDER BY MOVIMENTO ASC

/* PROFESSOR */

SELECT
	VENDEDOR AS VENDEDOR,
	CAST(AVG(VENDA_LIQUIDA) AS NUMERIC (15,2)) AS MEDIA_VENDAS,
	CASE
		WHEN QUANTIDADE < 0
			THEN 'Devolução'
		ELSE 'Venda_Externa'
	END AS TIPO_VENDA
FROM VENDAS_ANALITICAS
	WHERE VENDEDOR = 16
		AND MOVIMENTO >= '01/01/2020'
GROUP BY
	VENDEDOR,
		CASE
			WHEN QUANTIDADE < 0
				THEN 'Devolução'
			WHEN OPERACAO_FISCAL IN(12,14)
				THEN 'Venda Interna'
		ELSE 'Venda Externa'
	END
