SELECT * FROM CLIENTES


INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO)
VALUES ('Erbert Alves Gomes','12095470694','19/03/1993')

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO)
VALUES ('Patrícia Duarte', '1189547068','18/09/1975')

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO)
VALUES ('Glauber Moreno', '11995470698', '16/05/1992')

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO)
VALUES ('Alan Towersey', '11795470694', '16/09/1993')

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO)
VALUES ('Bono', '11201502069', '27/01/1995')

INSERT INTO CLIENTES (NOME, CPF, DATA_NASCIMENTO)
VALUES ('Indra', '11995470684', '15/04/1991')




SELECT*FROM CLIENTES

/* MÓDULO 05 */

SP_HELP PRODUTOS

/* RELACIONAMENTO INNER JOIN*/

SELECT 
	VENDEDOR
	FROM VENDAS_ANALITICAS


SELECT * FROM VENDEDORES

/* UTILIZANDO O INNER JOIN*/

SELECT
	A.VENDEDOR
FROM VENDAS_ANALITICAS A
	INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR


/* UTILIZANDO O INNER JOIN*/

SELECT
	A.VENDEDOR,
	B.NOME,
	SUM(A.QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS A
	INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY A.VENDEDOR, B.NOME
ORDER BY A.VENDEDOR


/* APLICANDO O FILTRO HAVING*/

SELECT
	A.VENDEDOR,
	B.NOME,
	SUM(A.QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS A
	INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
WHERE A.VENDEDOR IN(1,2,3,20)
GROUP BY A.VENDEDOR, B.NOME
HAVING SUM(A.QUANTIDADE) > 35840
ORDER BY A.VENDEDOR

/* OLHANDO PELA TABELA DE PRODUTOS */

SELECT
	A.PRODUTO,
	A.DESCRICAO,
	A.FAMILIA_PRODUTO,
	B.DESCRICAO
FROM PRODUTOS A
	INNER JOIN FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO

/* RELACIONANDO 3 TABELAS */

SELECT
	A.PRODUTO,
	B.DESCRICAO,
	C.DESCRICAO,
	A.QUANTIDADE
FROM VENDAS_ANALITICAS A
JOIN PRODUTOS B ON A.PRODUTO = B.PRODUTO
JOIN FAMILIAS_PRODUTOS C ON B.FAMILIA_PRODUTO = C.FAMILIA_PRODUTO

/* ANALISANDO QUANTO QUE EU VENDI POR FAMÍLIA */

SELECT
	C.DESCRICAO AS FAMILIA,
	SUM(A.QUANTIDADE)
FROM VENDAS_ANALITICAS A
JOIN PRODUTOS B ON A.PRODUTO = B.PRODUTO
JOIN FAMILIAS_PRODUTOS C ON B.FAMILIA_PRODUTO = C.FAMILIA_PRODUTO
GROUP BY C.DESCRICAO

/* REVISANDO */

SELECT
	A.VENDEDOR,
	B.NOME
FROM VENDAS_ANALITICAS A
	INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR

/* ADICIONANDO MAIS ALGUMAS COISAS */

SELECT
	A.VENDEDOR,
	B.NOME,
SUM(A.QUANTIDADE) AS QUANTIDADE
FROM VENDAS_ANALITICAS A
	INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
WHERE A.VENDEDOR IN(1,2,3,20)
GROUP BY A.VENDEDOR, B.NOME
HAVING SUM(A.QUANTIDADE) > 35840
ORDER BY A.VENDEDOR


/* OUTRAS TABELAS*/


SELECT
	PRODUTO,
	DESCRICAO,
	FAMILIA_PRODUTO
FROM PRODUTOS

SELECT
	A.PRODUTO,
	A.DESCRICAO,
	A.FAMILIA_PRODUTO,
	B.DESCRICAO
FROM PRODUTOS A
	JOIN FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO

/* COLOCANDO QUANTO QUE EU VENDI POR FAMÍLIA*/
SELECT
	A.PRODUTO,
	SUM(A.QUANTIDADE) AS QUANTIDADE,
	B.DESCRICAO,
	C.DESCRICAO
FROM VENDAS_ANALITICAS A
 JOIN PRODUTOS B ON A.PRODUTO = B.PRODUTO
 JOIN FAMILIAS_PRODUTOS C ON B.FAMILIA_PRODUTO = C.FAMILIA_PRODUTO
GROUP BY A.PRODUTO, B.DESCRICAO, C.DESCRICAO


/* DESAFIO */
/* RECUPERE O TOTAL VENDIDO POR MARCA DO PRODUTO SABENDO QUE...
1. O TOTAL VENDIDO CORRESPONDE A COLUNA VENDA_LIQUIDA DA TABELA VENDAS_ANALITICAS
2. A COLUNA PRODUTO FAZ RELAÇÃO COM A TABELA DE PRODUTOS ATRAVÉS DA COLUNA PRODUTO

1 - CÓDIGO DA MARCA
2 - DESCRIÇÃO DA MARCA
3 - TOTAL DA VENDA LÍQUIDA

REALIZE A ORDENAÇÃO DO RESULTADO PELO CÓDIDO DA MARCA */

SELECT
	SUM(A.VENDA_LIQUIDA) AS TOTAL_VENDIDO,
	A.PRODUTO AS PROD_VENDAS,
	B.MARCA AS COD_MARCA,
	B.DESCRICAO AS DESCRICAO
FROM VENDAS_ANALITICAS A
INNER JOIN PRODUTOS B ON A.PRODUTO = B.PRODUTO
GROUP BY A.PRODUTO, B.MARCA, B.DESCRICAO
ORDER BY B.MARCA ASC

SELECT * FROM PRODUTOS


/* LEFT JOIN */

SELECT
	A.PRODUTO,
	A.DESCRICAO,
	A.FAMILIA_PRODUTO,
	B.DESCRICAO
FROM PRODUTOS A
	LEFT JOIN FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO


SELECT
	PRODUTO
FROM PRODUTOS

SELECT 
	A.PRODUTO,
	A.FAMILIA_PRODUTO,
	A.DESCRICAO,
	B.DESCRICAO
FROM PRODUTOS A
 INNER JOIN FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO

SP_HELP PRODUTOS

SELECT
	A.PRODUTO,
	A.FAMILIA_PRODUTO,
	A.DESCRICAO AS TAB_PRODUTO,
	B.DESCRICAO AS TAB_FAMILIA,
	B.FAMILIA_PRODUTO
FROM PRODUTOS A
LEFT JOIN FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO
ORDER BY PRODUTO ASC

/* AULA DE LEFT JOIN */

SELECT
	A.PRODUTO,
	A.DESCRICAO,
	A.FAMILIA_PRODUTO AS TAB_PRODUTOS,
	COALESCE(B.DESCRICAO, 'NÃO ENCONTRADO') AS TAB_FAMILIAS_PRODUTOS
FROM PRODUTOS A
LEFT JOIN FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO


/* REVISANDO LEFT JOIN */

SELECT
	A.PRODUTO,
	A.DESCRICAO,
	A.FAMILIA_PRODUTO,
	B.DESCRICAO AS TAB_B
FROM PRODUTOS A
LEFT JOIN FAMILIAS_PRODUTOS B ON A.FAMILIA_PRODUTO = B.FAMILIA_PRODUTO

/* APLICANDO COM 3 TABELAS */
SELECT
	SUM(A.QUANTIDADE) AS SOMA_QTD,
	A.PRODUTO,
	C.DESCRICAO AS FAMILIA
FROM VENDAS_ANALITICAS A
INNER JOIN PRODUTOS B ON A.PRODUTO = B.PRODUTO
LEFT JOIN FAMILIAS_PRODUTOS C ON B.FAMILIA_PRODUTO = C.FAMILIA_PRODUTO
GROUP BY A.PRODUTO, C.DESCRICAO

SELECT
	PRODUTO,
	FAMILIA_PRODUTO
FROM PRODUTOS

/* DESAFIO */
-- RECUPERE A QUANTIDADE DE PRODUTOS E A MÉDIA DE VENDAS POR FABRICANTE DE ACORDO COM SEGUINTES CRITÉTICOS
-- TABELA VENDAS_ANALITICAS

-- O FABRICANTE ESTÁ NA TABELA DE PRODUTOS

-- CODIGO DO FABRICANTE,NOME DO FABRICANTE, QTDE DE PRODUTOS CADASTRADOS POR FABRICANTE
 -- MEDIA DE VENDAS DO FABRICANTE

 -- CASO O PRODUTO NÃO TENHA FABRICANTE, DEVE SER INFORMADO COMO FABRICANTE NÃO IDENTIFICADO
 -- ORDENE PELO FABRICANTE QUE TEM A MELHOR MÉDIA DE VENDAS

SELECT
	A.QUANTIDADE AS QTD_TAB_A,
	A.PRODUTO AS PROD_TAB_A,
	COALESCE(CAST(B.FABRICANTE AS VARCHAR),'NÃO IDENTIFICADO') AS FABR_TAB_B,
	AVG(A.VENDA_LIQUIDA) AS MEDIA_TAB
FROM VENDAS_ANALITICAS A
LEFT JOIN PRODUTOS B ON A.PRODUTO = B.PRODUTO
GROUP BY A.QUANTIDADE, A.PRODUTO, B.FABRICANTE
ORDER BY MEDIA_TAB DESC

/* RIGHT JOIN */


SELECT
	B.FABRICANTE,
	COUNT(DISTINCT B.PRODUTO) AS QUANTIDADE_PRODUTOS,
	AVG(A.VENDA_LIQUIDA) AS MEDIA_VENDAS
FROM VENDAS_ANALITICAS A
RIGHT JOIN PRODUTOS B ON A.PRODUTO = B.PRODUTO
GROUP BY B.FABRICANTE



/* FULL JOIN */

-- Trás tudo de ambas as tabelas, vendedores com venda e sem venda

/* Testando com INNER */

SELECT
	A.VENDEDOR,
	B.VENDEDOR
FROM VENDAS_ANALITICAS A
 INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR

/* Testando com LEFT JOIN*/

SELECT
	A.VENDEDOR AS TAB_VENDAS,
	B.VENDEDOR AS TAB_VENDEDORES
FROM VENDAS_ANALITICAS A
LEFT JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR

/* RIGHT JOIN */

SELECT
	A.VENDEDOR AS TAB_VENDAS,
	B.VENDEDOR AS TAB_VENDEDORES
FROM VENDAS_ANALITICAS A
RIGHT JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR

/* APLICANDO O DISTINCT */

-- Para vermos somente as possibilidades que não se repetem

SELECT DISTINCT
	A.VENDEDOR AS TAB_VENDAS,
	B.VENDEDOR  AS TAB_VENDEDORES
FROM VENDAS_ANALITICAS A
INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
ORDER BY TAB_VENDAS

/* Aplicando com FULL JOIN */

SELECT DISTINCT
 A.VENDEDOR AS TAB_VENDAS,
 B.VENDEDOR AS TAB_VENDEDORES
FROM VENDAS_ANALITICAS A
FULL JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR


/* APLICAÇÃO REFINADA */

SELECT
	COALESCE(A.VENDEDOR, B.VENDEDOR) AS VENDEDOR,
	ISNULL(SUM(A.QUANTIDADE),0 ) AS QTD
FROM VENDAS_ANALITICAS A
FULL JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY COALESCE(A.VENDEDOR, B.VENDEDOR)
ORDER BY COALESCE(A.VENDEDOR, B.VENDEDOR)

/*  TODAS AS VENDAS POR VENDEDORES E OS VENDEDORES SEM VENDA */

SELECT
	COALESCE(A.VENDEDOR, B.VENDEDOR) AS VENDEDOR,
	ISNULL(SUM(A.QUANTIDADE),0) AS QTD
FROM VENDAS_ANALITICAS A
FULL JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY COALESCE(A.VENDEDOR, B.VENDEDOR)
ORDER BY COALESCE(A.VENDEDOR, B.VENDEDOR)

/* DESAFIO FULL JOIN */

-- Busque todas as vendas e todos os clientes que ainda não realizaram compras
-- consulta deverá trazer o cód.cliente, nome do cliente e o total vendido (venda_liquida)
-- Trazer Tabelas vendas_analiticas e entidades, elas se relacionam por meio da coluna cliente e entidade da tabela entidades
-- essa coluna cliente é da tabela vendas_analíticas
-- a coluna entidade é da tabela entidades
-- ordene os clientes que teve mais vendas para o que teve menos vendas

SELECT
	A.CLIENTE,
	SUM(A.VENDA_LIQUIDA) AS TAB_VENDAS,
	B.ENTIDADE,
	B.NOME
FROM VENDAS_ANALITICAS A
FULL JOIN ENTIDADES B ON A.CLIENTE = B.ENTIDADE
GROUP BY A.CLIENTE, B.ENTIDADE, B.NOME
ORDER BY A.CLIENTE DESC

SELECT * FROM ENTIDADES

/* TREINO FULL JOIN */

 -- TODAS AS VENDAS POR VENDEDORES E OS VENDEDORES SEM VENDA
 -- TAB VENDAS_ANALITICAS E VENDEDORES: COLUNA EM COMUM - VENDEDORES

 -- ANALISANDO POR INNER
 -- PEGANDO SOMENTE AS VENDAS QUE TÊM VENDEDORES

 SELECT
	A.VENDEDOR AS TAB_VENDAS,
	SUM(A.QUANTIDADE) AS TAB_VENDAS,
	B.VENDEDOR AS TAB_VENDEDORES
FROM VENDAS_ANALITICAS A
INNER JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY A.VENDEDOR, B.VENDEDOR

-- TESTANDO COM LEFT JOIN
-- TRAZEMOS VENDAS COM VENDEDORES, VENDAS SEM  VENDEDORES, OU SEJA VENDAS COM E SEM VENDEDORES
-- MAS OS VENDEDORES QUE NÃO TÊM VENDAS NÃO VÃO APARECER NA RELAÇÃO
SELECT
	A.VENDEDOR AS TAB_VENDAS,
	SUM(A.QUANTIDADE) AS TAB_VENDAS,
	B.VENDEDOR AS TAB_VENDEDORES
FROM VENDAS_ANALITICAS A
LEFT JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY A.VENDEDOR, B.VENDEDOR

-- TESTANDO COM RIGHT JOIN
-- AQUI TRAZEMOS VENDAS COM VENDEDORES, MAS APARECEM OS VENDEDORES COM E SEM VENDAS.
-- NÃO APARECEM AS VENDAS SEM VENDEDORES

SELECT
	A.VENDEDOR AS TAB_VENDAS,
	B.VENDEDOR AS TAB_VENDEDORES,
	SUM(A.QUANTIDADE) AS TAB_VENDAS
FROM VENDAS_ANALITICAS A
RIGHT JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY A.VENDEDOR, B.VENDEDOR

SELECT *
	--VENDEDOR
FROM VENDAS_ANALITICAS

SELECT
	VENDEDOR
FROM VENDEDORES

/* FULL JOIN COM O PROF*/

SELECT
	COALESCE(A.VENDEDOR, B.VENDEDOR) AS VENDEDOR,
	ISNULL(SUM(A.QUANTIDADE),0) AS QTDE
FROM VENDAS_ANALITICAS A
FULL JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY COALESCE(A.VENDEDOR, B.VENDEDOR)
ORDER BY COALESCE(A.VENDEDOR, B.VENDEDOR)

/* CONTORNANDO ISSO COM A IDEIA DE QUE A TABELA VENDEDORES É UMA TABELA DIMENSÃO) */
/* ENTÃO ELA FICA NO EIXO DE VISUALIZAÇÃO, E O GROUP BY É FEITO POR ELA*/

SELECT
	B.VENDEDOR AS VENDEDOR_TAB_VENDEDORES,
	ISNULL(SUM(A.QUANTIDADE),0) AS QTDE
FROM VENDAS_ANALITICAS A
FULL JOIN VENDEDORES B ON A.VENDEDOR = B.VENDEDOR
GROUP BY B.VENDEDOR
ORDER BY B.VENDEDOR