USE PBS_PROCFIT_DADOS

SELECT
	PRODUTO,
	QUANTIDADE,
	VALOR_UNITARIO,
	QUANTIDADE * VALOR_UNITARIO AS VALOR_TOTAL_PRODUTO,
	ICMS_ALIQUOTA,
	(QUANTIDADE * VALOR_UNITARIO) * (ICMS_ALIQUOTA/100) AS ICMS_VALOR

FROM NF_FATURAMENTO_PRODUTOS

/* Concatenando valores*/

SELECT
	CIDADE,
	ESTADO,
	CIDADE +'-' +  ESTADO AS ENDERECO_COMPLETO
	FROM ENDERECOS

/* CONCAT NUNCA SOMA, APENAS JUNTA OS VALORES*/

SELECT '5' + '2' /* retorna 52*/
SELECT 5 + 2 /* retorna 7*/
SELECT CONCAT(5,2) /* retorna 52*/

SELECT  CONCAT ('Erbert',  'Alves',  'Gomes')

SELECT
	CIDADE,
	ESTADO,
	CONCAT(CIDADE,'-',ESTADO)
FROM ENDERECOS


/*DESAFIO*/
/* Campo ENTIDADE CONCATENADO COM O CAMPO NOME_FANTASIA*/

SELECT
	ENTIDADE,
	NOME_FANTASIA,
	CONCAT(ENTIDADE,'-',NOME_FANTASIA)
FROM ENTIDADES

/*Na tabela PRODUTOS CONCATENE O CAMPO DECRICAO COM O CAMPO UNIDADE_MEDIDA*/

SELECT
	DESCRICAO,
	UNIDADE_MEDIDA,
	CONCAT(DESCRICAO,'-',UNIDADE_MEDIDA) AS CONCATENACAO
FROM PRODUTOS

/* RESOLVENDO POR MEIO DO OPERADOR + */
/*Campo entidade concatenando com o campo nome fantasia*/

SELECT
	ENTIDADE,
	NOME_FANTASIA,
	ENTIDADE  + '-' + NOME_FANTASIA AS CONCA
FROM ENTIDADES
SP_HELP ENTIDADES

/*exercício 2*/

SELECT
	DESCRICAO,
	UNIDADE_MEDIDA,
	DESCRICAO +'-'+UNIDADE_MEDIDA
FROM PRODUTOS

/* MÓDULO 07 - SUBQUERIES */

SELECT * FROM (
SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER,
	0.00 AS VALOR_PAGAR	
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE,
	0.00 AS VALOR_RECEBER,
	SUM(VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE

) A
ORDER BY ENTIDADE

/* DEIXANDO A CONSULTA MAIS COMPLETA */

  SELECT
	A.ENTIDADE,
	B.NOME,
	SUM(A.VALOR_RECEBER) AS VALOR_RECEBER,
	SUM(A.VALOR_PAGAR) AS VALOR_PAGAR,
	SUM(A.VALOR_RECEBER) - SUM(A.VALOR_PAGAR) AS SALDO

	FROM (
SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER,
	0.00 AS VALOR_PAGAR	
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE,
	0.00 AS VALOR_RECEBER,
	SUM(VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE

) A
JOIN ENTIDADES B  ON A.ENTIDADE = B.ENTIDADE
GROUP BY A.ENTIDADE, B.NOME
ORDER BY ENTIDADE


/* REVISANDO */

SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER,
	0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE,
	0.00 AS VALOR_RECEBER,
	SUM(VALOR) AS VALOR_PÁGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE

ORDER BY ENTIDADE

/* SUBQUERY É UM SELEC DENTRO DO OUTRO*/
/* O ORDER BY FICA PRA FORA DA SUBQUERY */

SELECT * FROM
(
SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER, 
	0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE, 
	0.00 AS VALOR_RECEBER,
	SUM(VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE
) AS A
ORDER BY ENTIDADE

/* AQUI ESTAMOS UTILIZANDO FUNÇÕES DE AGRAGAÇÕES DAS FUNÇÕES QUE ESTÃO DENTRO DA NOSSA SUBQUERY */
/* UNIFICAMOS 2 LINHAS EM UMA */

SELECT
	A.ENTIDADE,
	SUM(A.VALOR_RECEBER) AS VALOR_RECEBER,
	SUM(A.VALOR_PAGAR) AS VALOR_PAGAR,
	SUM(A.VALOR_RECEBER) - SUM(A.VALOR_PAGAR) AS SALDO
FROM (
SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER,
	0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE, 
	0.00 AS VALOR_RECEBER,
	SUM(VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE

) AS A
GROUP BY A.ENTIDADE
ORDER BY A.ENTIDADE

/* SABENDO QUE TABELAS SÃO FONTES DE DADOS, E SUBQUERIES TAMBÉM, ENTÃO PODEMOS FAZER JOIN*/

SELECT
    B.NOME,
	A.ENTIDADE,
	SUM(A.VALOR_RECEBER) AS VALOR_RECEBER,
	SUM(A.VALOR_PAGAR) AS VALOR_PAGAR,
	SUM(A.VALOR_RECEBER) - SUM(A.VALOR_PAGAR) AS SALDO

FROM
(
SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER,
	0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE,
	0.00 AS VALOR_RECEBER,
	SUM(VALOR) AS VALOR_PÁGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE
) AS A

JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE

GROUP BY A.ENTIDADE, B.NOME
ORDER BY A.ENTIDADE

/* UTILIZANDO MÚLTIPLAS SUBQUERIES NO MESMO COMANDO SELECT */

SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE

/* APLICANDO LEFT JOIN */

SELECT
	A.ENTIDADE,
	A.NOME,
	ISNULL(B.VALOR_RECEBER,0) AS VALOR_RECEBER,
	ISNULL(C.VALOR_PAGAR,0) AS VALOR_PAGAR,
	ISNULL(B.VALOR_RECEBER,0) - ISNULL(C.VALOR_PAGAR,0) AS SALDO
FROM ENTIDADES A 
LEFT JOIN ( -- LEFT JOIN APLICADO NA NA TABELA TITULO_RECEBER PARA VERMOS SE O CLIENTE TEM TÍTULOS A RECEBER
 SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER
FROM TITULOS_RECEBER
GROUP BY ENTIDADE
)  B ON A.ENTIDADE = B.ENTIDADE

LEFT JOIN ( -- LEFT JOIN APLICADO NA TABELA TITULO_PAGAR PARA VERMOS SE O CLIENTE TEM TÍTULOS A PAGAR

SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE
) C ON A.ENTIDADE = C.ENTIDADE

WHERE B.VALOR_RECEBER IS NOT NULL OR C.VALOR_PAGAR IS NOT NULL

/* REVISANDO */
SELECT
    B.NOME,
	A.ENTIDADE,
	SUM(A.VALOR_RECEBER) AS VALOR_RECEBER,
	SUM(A.VALOR_PAGAR) AS VALOR_PAGAR,
	SUM(A.VALOR_RECEBER) - SUM(A.VALOR_PAGAR) AS SALDO
	FROM(
SELECT
	ENTIDADE,
	SUM(VALOR) AS VALOR_RECEBER,
	0.00 AS VALOR_PAGAR
FROM TITULOS_RECEBER
GROUP BY ENTIDADE

UNION ALL

SELECT
	ENTIDADE, 
	0.00 AS VALOR_RECEBER,
	SUM(VALOR) AS VALOR_PAGAR
FROM TITULOS_PAGAR
GROUP BY ENTIDADE
) A
JOIN ENTIDADES B ON A.ENTIDADE = B.ENTIDADE
GROUP BY A.ENTIDADE, B.NOME
ORDER BY A.ENTIDADE

/* REVISANDO  - UTILIZANDO MÚLTIPLICAS SUBQUERIES NO MESAMO COMANDO SEELCT */

SELECT
	A.ENTIDADE,
	A.NOME,
	B.VALOR_RECEBER
FROM ENTIDADES A
LEFT JOIN (
	SELECT
		ENTIDADE,
		SUM(VALOR) AS VALOR_RECEBER
	FROM TITULOS_RECEBER
		GROUP BY ENTIDADE
		) B ON A.ENTIDADE = B.ENTIDADE

LEFT JOIN (
	SELECT
		ENTIDADE,
		SUM(VALOR) AS VALOR_PAGAR
	FROM TITULOS_PAGAR
     GROUP BY ENTIDADE
	 ) C ON A.ENTIDADE = C.ENTIDADE

SELECT
	 NOME
FROM
	 ENTIDADES


SELECT
	A.ENTIDADE,
	A.NOME,
	ISNULL(B.VALOR_RECEBER, 0) AS VALOR_RECEBER,
	ISNULL(C.VALOR_PAGAR,0) AS VALOR_PAGAR,
	ISNULL(B.VALOR_RECEBER,0) - ISNULL(C.VALOR_PAGAR,0) AS SALDO
FROM ENTIDADES A

LEFT JOIN (
	SELECT
		ENTIDADE,
		SUM(VALOR) AS VALOR_RECEBER
	FROM TITULOS_RECEBER
GROUP BY ENTIDADE) B ON A.ENTIDADE = B.ENTIDADE

LEFT JOIN (
	SELECT
		ENTIDADE,
		SUM(VALOR) AS VALOR_PAGAR
	FROM TITULOS_PAGAR
GROUP BY ENTIDADE)
C ON A.ENTIDADE = C.ENTIDADE

WHERE B.VALOR_RECEBER IS NOT NULL
OR C.VALOR_PAGAR IS NOT NULL

/* UTILIZANDO OS OPERADORES IN E NOT IN */

-- Vamos supor que a gente queira trazer somente os clientes que compraram em 2019

SELECT
	CLIENTE
FROM VENDAS_ANALITICAS
WHERE YEAR(MOVIMENTO) = 2019 -- ESSA QUERY ME TRÁS TODOS OS CÓDIGOS DOS CLIENTES QUE COMPRARM EM 2019

-- UTILIZANDO O CÓDIGO ACIMA COMO SUBQUERY

SELECT
	A.ENTIDADE,
	A.NOME,
	B.ESTADO
FROM ENTIDADES A
INNER JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
WHERE A.ENTIDADE IN(
   SELECT
	   CLIENTE
	FROM VENDAS_ANALITICAS
	WHERE YEAR(MOVIMENTO) = 2019
	)

/* REVISANDO A APLICAÇÃO DE IN E NOT IN COMO SUBQUERY */

SELECT
	A.ENTIDADE,
	A.NOME,
	B.ESTADO
FROM ENTIDADES A
JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
WHERE A.ENTIDADE IN(
	SELECT
		CLIENTE
	FROM VENDAS_ANALITICAS
	WHERE YEAR(MOVIMENTO) = 2019
	) -- SUBQUERY QUE ME RETORNA SOMENTE OS CLIENTES DE 2019


	/* UTILIZANDO SUBQUERIES COM OS OPERADORES DE COMPARAÇÃO */

	-- IDENTIFICANDO O CLIENTE QUE MAIS COMPROU
SELECT
	CLIENTE,
	SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA
FROM VENDAS_ANALITICAS
GROUP BY CLIENTE
ORDER BY VENDA_LIQUIDA DESC

/* PASSANDO O CLIENTE 1876 COMO FOMRA DE FILTRO */

SELECT
	A.ENTIDADE,
	A.NOME,
	B.ESTADO
FROM ENTIDADES A
JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
WHERE A.ENTIDADE = 1876

/* APLICANDO O TOP 1 PARA TRAZERMOS O CLIENTE QUE MAIS VENDEU, DE FORMA AUTOMÁTICA */

SELECT TOP 1
	CLIENTE
FROM VENDAS_ANALITICAS
GROUP BY CLIENTE
ORDER BY SUM(VENDA_LIQUIDA) DESC


/* UTILIZANDO SUBQUERIES COM OS OPERADORES DE COMPARAÇÃO - REVISÃO */


SELECT
	A.ENTIDADE,
	A.NOME,
	B.ESTADO
FROM ENTIDADES A
	JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
WHERE A.ENTIDADE = (
					SELECT
						CLIENTE
					FROM VENDAS_ANALITICAS
					WHERE YEAR(MOVIMENTO) = 2019 -- AQUI VAI RETORNAR UM ERRO, PORQUE  A CONSULTA RETORNOU MAIS DE UM VALOR.
					)


-- VERIFICANDO O CLIENTE QUE MAIS COMPROU
SELECT
	CLIENTE,
SUM(VENDA_LIQUIDA) AS VENDA_LIQUIDA
FROM VENDAS_ANALITICAS
GROUP BY CLIENTE
ORDER BY VENDA_LIQUIDA DESC


-- MAS TEMMOS UM PROBLEMA, NEM SEMPRE O CLIENTE QUE MAIS COMPROU VAI SER O CLIENTE DE CÓDIGO 1876

-- DEIXANDO ISSO DE FORMA AUTOMÁTICA
-- AQUI ESTAMOS FAZENDO O TOP 1 DE ACORDO COM A ORDENAÇÃO DO ORDER BY

SELECT TOP 1
	CLIENTE
FROM VENDAS_ANALITICAS
GROUP BY CLIENTE
ORDER BY SUM(VENDA_LIQUIDA) DESC -- COLOCANDO ISSO AGORA DENTRO DA CLÁUSULA WHERE

SELECT
	A.ENTIDADE,
	A.NOME,
	B.ESTADO
FROM ENTIDADES A
INNER JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
WHERE A.ENTIDADE = (
		SELECT TOP 1
			CLIENTE
		FROM VENDAS_ANALITICAS
		GROUP BY CLIENTE
		ORDER BY SUM(VENDA_LIQUIDA) DESC
		)

-- TRAZENDO O RESULTADO DIFERNTE DO CLIENTE QUE MAIS COMPROU <>

SELECT
	A.ENTIDADE,
	A.NOME,
	B.ESTADO
FROM ENTIDADES A
INNER JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
WHERE A.ENTIDADE <> (
	SELECT TOP 1
		CLIENTE
	FROM VENDAS_ANALITICAS
	GROUP BY CLIENTE
	ORDER BY SUM(VENDA_LIQUIDA) DESC
)

/* RELACIONANDO TABELAS NA CLÁUSULA WHERE */

SELECT * FROM ENTIDADES A
INNER JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE


-- ESSA CONSULTA DE CIMA TRÁS O MESMO RESULTADO DESSA DE BAIXO

SELECT * FROM ENTIDADES A, ENTIDADES B
WHERE A.ENTIDADE = B.ENTIDADE 

/* EXISTS E NOT EXISTS */

SELECT
	A.ENTIDADE,
	A.NOME
FROM ENTIDADES A
LEFT JOIN TITULOS_PAGAR B ON A.ENTIDADE = B.ENTIDADE
WHERE B.TITULO_PAGAR IS NULL -- AQUI ESTAMOS PEGANDO TODOS OS CLIENTES QUE NÃO TÊM TÍTULOS A PAGAR

-- OUTRA FORMA DE SE OBTER ISSO É POR MEIO DO NOT IN

SELECT
	A.ENTIDADE,
	A.NOME
FROM ENTIDADES A
WHERE A.ENTIDADE NOT IN(
						SELECT DISTINCT
									ENTIDADE
						FROM TITULOS_PAGAR
						)

-- FAZENDO COM NOT EXISTS

SELECT
	A.ENTIDADE,
	A.NOME,
	B.ESTADO
FROM ENTIDADES A
INNER JOIN ENDERECOS B ON A.ENTIDADE = B.ENTIDADE
WHERE NOT EXISTS(
			SELECT * FROM TITULOS_PAGAR X
			WHERE A.ENTIDADE = X.ENTIDADE
			)
