USE PBS_PROCFIT_DADOS

SELECT
	PRODUTO,
	QUANTIDADE,
	VALOR_UNITARIO,
	QUANTIDADE * VALOR_UNITARIO AS VALOR_TOTAL_PRODUTO,
	ICMS_ALIQUOTA,
	(QUANTIDADE * VALOR_UNITARIO) * (ICMS_ALIQUOTA/100) AS ICMS_VALOR

FROM NF_FATURAMENTO_PRODUTOS

/* Concatenando valores*/

SELECT
	CIDADE,
	ESTADO,
	CIDADE +'-' +  ESTADO AS ENDERECO_COMPLETO
	FROM ENDERECOS

/* CONCAT NUNCA SOMA, APENAS JUNTA OS VALORES*/

SELECT '5' + '2' /* retorna 52*/
SELECT 5 + 2 /* retorna 7*/
SELECT CONCAT(5,2) /* retorna 52*/

SELECT  CONCAT ('Erbert',  'Alves',  'Gomes')

SELECT
	CIDADE,
	ESTADO,
	CONCAT(CIDADE,'-',ESTADO)
FROM ENDERECOS


/*DESAFIO*/
/* Campo ENTIDADE CONCATENADO COM O CAMPO NOME_FANTASIA*/

SELECT
	ENTIDADE,
	NOME_FANTASIA,
	CONCAT(ENTIDADE,'-',NOME_FANTASIA)
FROM ENTIDADES

/*Na tabela PRODUTOS CONCATENE O CAMPO DECRICAO COM O CAMPO UNIDADE_MEDIDA*/

SELECT
	DESCRICAO,
	UNIDADE_MEDIDA,
	CONCAT(DESCRICAO,'-',UNIDADE_MEDIDA) AS CONCATENACAO
FROM PRODUTOS

/* RESOLVENDO POR MEIO DO OPERADOR + */
/*Campo entidade concatenando com o campo nome fantasia*/

SELECT
	ENTIDADE,
	NOME_FANTASIA,
	ENTIDADE  + '-' + NOME_FANTASIA AS CONCA
FROM ENTIDADES
SP_HELP ENTIDADES

/*exercício 2*/

SELECT
	DESCRICAO,
	UNIDADE_MEDIDA,
	DESCRICAO +'-'+UNIDADE_MEDIDA
FROM PRODUTOS

/* TABELAS TEMPORÁRIAS */

CREATE TABLE ##tblTemporaria
(
	cod_cliente INT,
	nome_cliente VARCHAR(60),
	total_vendido MONEY,
	)


/* CRIANDO TABELA TEMPORÁRIA */
SELECT
	B.ENTIDADE AS COD_CLIENTE,
	B.NOME AS NOME_CLIENTE,
	SUM(A.VENDA_LIQUIDA) AS TOTAL_VENDIDO
INTO #tblClientesVenda
FROM VENDAS_ANALITICAS AS A
JOIN ENTIDADES B ON A.CLIENTE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME


SELECT * FROM #tblClientesVenda


/* RECUPERAR O TOTAL A PAGAR E O VALOR PAGO POR ANO E MÊS DE CADA ENTIDADE */
/* RECUPERAR O TOTAL A RECEBER E O VALOR RECEBIDO POR ANO E MÊS DE CADA ENTIDADE */
/* RECUPERAR TODAS AS VENDAS POR ANO E MÊS DE CADA ENTIDADE */

SELECT
	YEAR(A.MOVIMENTO) AS ANO,
	MONTH(A.MOVIMENTO) AS MÊS,
	SUM(A.VALOR) AS TOTAL_PAGAR,
	SUM(B.SALDO) AS SALDO_DEVEDOR,
	SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_PAGAR A
JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)

/* MELHORANDO O CÓDIGO - TOTAL A PAGAR PARA O CLIENTE */

SELECT
	YEAR(A.MOVIMENTO) AS ANO,
	MONTH(A.MOVIMENTO) AS MÊS,
CASE
	WHEN SUM(A.VALOR) < SUM(B.SALDO)
	THEN SUM(B.SALDO)	
	ELSE SUM(A.VALOR)
END AS TOTAL_PAGAR,
SUM(B.SALDO) AS SALDO_DEVEDOR,

CASE
	WHEN SUM(A.VALOR) < SUM (B.SALDO)
	THEN SUM(B.SALDO)
	ELSE SUM(A.VALOR)
END - SUM(B.SALDO) AS TOTAL_PAGO

FROM TITULOS_PAGAR A
JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)


/* TOTAL RECEBIDO DO CLIENTE */

SELECT
	YEAR(A.MOVIMENTO) AS ANO,
	MONTH(A.MOVIMENTO) AS MES,
	SUM(A.VALOR) AS TOTAL_RECEBER,
	SUM(B.SALDO) AS SALDO_RECEBER,
	SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_RECEBIDO
FROM TITULOS_RECEBER A
INNER JOIN TITULOS_RECEBER_SALDO B ON A.TITULO_RECEBER = B.TITULO_RECEBER
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)

/* REVISÃO */ -- Ah lá, ah lá, cê já viu quem tá ali...

 -- Tabela temporária só funciona dentro de um contexto que ela foi criada, dentro daquela janela de execução, se você fechar a janela, você perde tudo
 -- Tabela temporária global funciona em qualquer janela de execução
 -- A tabela temporária comum só funciona com o usuário que a criou, a global, não.

 /* CRIANDO NOSSAS PRIMEIRAS TABELAS TEMPORÁRIAS */

 CREATE TABLE ##tblTemporaria

 (
	cod_cliente INT,
	nome_cliente VARCHAR(80),
	total_vendido MONEY
	)

INSERT INTO ##tblTemporaria (cod_cliente, nome_cliente, total_vendido)
VALUES
	(1,'João da Silva Sauro',1500),
	(2,'Maria de Souza',25000),
	(3,'Carlos Maia',30000);



SELECT* FROM ##tblTemporaria

-- outra forma de criar tabela temporária, mas é menos performática

SELECT
	B.ENTIDADE AS COD_CLIENTE,
	B.NOME AS NOME_CLIENTE,
	SUM(A.VENDA_LIQUIDA) AS TOTAL_VENDIDO
FROM VENDAS_ANALITICAS A
INNER JOIN ENTIDADES B ON A.CLIENTE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME

-- AGORA VAMOS PASSAR ISSO TUDO ACIMA PARA A TEMPORÁRIA, BASTA COLOCAR UM INTO ANTES DO FROM

SELECT
	B.ENTIDADE AS COD_CLIENTE,
	B.NOME AS NOME_CLIENTE,
	SUM(A.VENDA_LIQUIDA) AS TOTAL_VENDIDO
INTO #tblClientesVendas
FROM VENDAS_ANALITICAS A
INNER JOIN ENTIDADES B ON A.CLIENTE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME

-- O CÓDIGO ACIMA POPULA A TABELA TEMPORÁRIA
-- DAQUI PRA FRENTE, A GENTE PODE FAZER AS MESMAS OPERAÇÕES COM A TABELA TEMPORÁRIA, COMO SE ELA FOSSE UMA TABELA COMUM

SELECT
	COD_CLIENTE,
	NOME_CLIENTE,
	TOTAL_VENDIDO
FROM #tblClientesVendas

/* TRABALHANDO COM TABELAS TEMPORÁRIAS PARTE 1 */
-- RECUPERAR O TOTAL A PAGAR O VALOR PAGO POR ANO E MÊS DE CADA ENTIDADE
-- RECUPERAR O TOTAL A RECEBER E O VALOR RECEBIDO POR ANO E MÊS DE CADA ENTIDADE
-- RECUPERAR TODAS AS VENDAS POR ANO E MÊS DE CADA ENTIDADE

SELECT
YEAR(A.MOVIMENTO) AS ANO,
MONTH(A.MOVIMENTO) AS MÊS,
SUM(A.VALOR) AS TOTAL_PAGAR,
SUM(B.SALDO) AS SALDO_DEVEDOR,
SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_PAGAR A
INNER JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)
ORDER BY ANO

-- APLICAÇÃO DO CASE WHEN
-- TODA VEZ QUE MINHA COLUNA TOTAL_PAGAR FOR IGUAL A ZERO, QUERO QUE TRAGA O VALOR DO SALDO_DEVEDOR

SELECT
YEAR(A.MOVIMENTO) AS ANO,
MONTH(A.MOVIMENTO) AS MÊS,
SUM(A.VALOR) AS TOTAL_PAGAR,
CASE
	WHEN
		SUM(A.VALOR) = 0
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
END AS TOTAL_PAGAR_2,
SUM(B.SALDO) AS SALDO_DEVEDOR,
SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_PAGAR A
INNER JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)
ORDER BY ANO

-- EVITAR QUE A COLUNA TOTAL_PAGO FIQUE COM VALORES NEGATIVOS, FAZEMOS:

SELECT
YEAR(A.MOVIMENTO) AS ANO,
MONTH(A.MOVIMENTO) AS MÊS,
SUM(A.VALOR) AS TOTAL_PAGAR,
CASE
	WHEN
		SUM(A.VALOR) = 0
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
END AS TOTAL_PAGAR_2,
SUM(B.SALDO) AS SALDO_DEVEDOR,
CASE
	WHEN
		SUM(A.VALOR) = 0
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
END - SUM(B.SALDO) AS TOTAL_PAGO,
SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_PAGAR A
INNER JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)
ORDER BY ANO

-- FAZENDO AGORA UM NOVO AJUSTE
SELECT
YEAR(A.MOVIMENTO) AS ANO,
MONTH(A.MOVIMENTO) AS MÊS,
SUM(A.VALOR) AS TOTAL_PAGAR,
CASE
	WHEN
		SUM(A.VALOR) < SUM(B.SALDO)
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
END AS TOTAL_PAGAR_2,
SUM(B.SALDO) AS SALDO_DEVEDOR,
CASE
	WHEN
		SUM(A.VALOR) < SUM(B.SALDO)
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
END - SUM(B.SALDO) AS TOTAL_PAGO,
SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_PAGAR A
INNER JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)
ORDER BY ANO

-- FAZENDO AGORA PARA TÍTULOS A RECEBER
-- TOTAL RECEBIDO DO CLIENTE
SELECT
YEAR(A.MOVIMENTO) AS ANO,
MONTH(A.MOVIMENTO) AS MÊS,
SUM(A.VALOR) AS TOTAL_PAGAR,
CASE
	WHEN
		SUM(A.VALOR) < SUM(B.SALDO)
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
END AS TOTAL_PAGAR_2,
SUM(B.SALDO) AS SALDO_DEVEDOR,
CASE
	WHEN
		SUM(A.VALOR) < SUM(B.SALDO)
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
END - SUM(B.SALDO) AS TOTAL_PAGO,
SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_RECEBER A
INNER JOIN TITULOS_RECEBER_SALDO B ON A.TITULO_RECEBER = B.TITULO_RECEBER
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)
ORDER BY ANO

-- COMO ESSA ESTRUTURA ESTÁ MAIS ORGANIZADA

SELECT
	 YEAR(A.MOVIMENTO) AS ANO,
	 MONTH(A.MOVIMENTO) AS MÊS,
	 SUM(A.VALOR) AS TOTAL_RECEBER,
	 SUM(B.SALDO) AS SALDO_RECEBER,
	 SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_RECEBIDO
FROM TITULOS_RECEBER A
INNER JOIN TITULOS_RECEBER_SALDO B ON A.TITULO_RECEBER = B.TITULO_RECEBER
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)

/* REVISANDO, REVISANDO...*/

SELECT
	B.ENTIDADE AS ENTIDADE,
	B.NOME AS NOME_CLIENTE,
	SUM(A.VENDA_ANALITICA) AS TOTAL_VENDIDO
INTO #tblClientesVendas
FROM VENDAS_ANALITICAS A
	INNER JOIN ENTIDADES B ON A.CLIENTE = B.ENTIDADE
GROUP BY B.ENTIDADE, B.NOME

-- CHAMANDO A TABELA TEMPORÁRIA

SELECT * FROM #tblClientesVendas

-- TRABALHANDO COM TABELAS TEMPORÁRIAS
-- RECUPERAR O TOTAL A PAGAR E O VALOR PAGO POR ANO E MÊS DE CADA ENTIDADE
SELECT
	YEAR(A.MOVIMENTO) AS ANO,
	MONTH(A.MOVIMENTO) AS MES,
	SUM(A.VALOR) AS TOTAL_PAGAR,
	CASE
		WHEN
			SUM(A.VALOR) < SUM(B.SALDO)
		THEN
			SUM(B.SALDO)
		ELSE
			SUM(A.VALOR)
	END AS TOTAL_PAGAR_2,
	SUM(B.SALDO) AS SALDO_DEVEDOR,
	CASE
		WHEN
			SUM(A.VALOR) < SUM(B.SALDO)
		THEN
			SUM(B.SALDO) 
		ELSE
			SUM(A.VALOR)
	END - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_PAGAR A
INNER JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO),MONTH(A.MOVIMENTO)


-- FAZENDO PARA TÍTULOS A RECEBER

SELECT
	YEAR(A.MOVIMENTO) AS ANO,
	MONTH(A.MOVIMENTO) AS MES,
	SUM(A.VALOR) AS TOTAL_RECEBER,
	SUM(B.SALDO) AS SALDO_RECEBER,
	SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_RECEBIDO
FROM TITULOS_RECEBER A
INNER JOIN TITULOS_RECEBER_SALDO B ON A.TITULO_RECEBER = B.TITULO_RECEBER
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)

/* TREINE, TREINE */

SELECT
	YEAR(A.MOVIMENTO) AS ANO,
	MONTH(A.MOVIMENTO) AS MES,
	SUM(A.VALOR) AS TOTAL_PAGAR,
	CASE
		WHEN
			SUM(A.VALOR) < SUM(B.SALDO)
		THEN 
		    SUM(B.SALDO)
		ELSE SUM(A.VALOR)
		END AS TOTAL_PAGAR_2,
	SUM(B.SALDO) AS SALDO_DEVEDOR,
	CASE
		WHEN
			SUM(A.VALOR) < SUM(B.SALDO)
		THEN
			SUM(B.SALDO)
		ELSE SUM(A.VALOR)
	END - SUM(B.SALDO) AS TOTAL_PAGO
FROM TITULOS_PAGAR A
	INNER JOIN TITULOS_PAGAR_SALDO B ON A.TITULO_PAGAR = B.TITULO_PAGAR
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)

--- ANALISANDO AGORA COMO SE A GENTE ESTIVESSE RECENDO DO CLIENTE

SELECT
	YEAR(A.MOVIMENTO) AS ANO,
	MONTH(A.MOVIMENTO) AS MES,
	SUM(A.VALOR) AS TOTAL_RECEBER,
	SUM(B.SALDO) AS SALDO_RECEBER,
	SUM(A.VALOR) - SUM(B.SALDO) AS TOTAL_RECEBIDO
FROM TITULOS_RECEBER A
INNER JOIN TITULOS_RECEBER_SALDO B ON A.TITULO_RECEBER = B.TITULO_RECEBER
GROUP BY YEAR(A.MOVIMENTO), MONTH(A.MOVIMENTO)

/* TRABALHANDO COM TABELAS TEMPORÁRIAS PARTE 2*/

-- RECUPERAR TODAS AS VENDAS POR ANO  E MÊS DE CADA ENTIDADE
